const GASTRO_DATA = [
 {
  "kat": "Catering dodavatel",
  "firma": "MENju s.r.o.",
  "ico": "53455339",
  "adresa": "Karpatske nam. 10A",
  "mesto": "Bratislava-Raca",
  "okres": "Bratislava",
  "velkost": "trzby 169 tis EUR (2025), 3-4 zam",
  "tel": "+421 908 368 968",
  "email": "event@menju.sk",
  "web": "menju.sk",
  "zona": "Z2",
  "pozn": "rozvoz do officu + teambuilding; prevadzka Tomasikova 17",
  "lat": 48.2161175,
  "lon": 17.1654827
 },
 {
  "kat": "Catering dodavatel",
  "firma": "TOMIR s.r.o. (MacoMenu)",
  "ico": "47981300",
  "adresa": "Bojnicka 10",
  "mesto": "Bratislava-Nove Mesto",
  "okres": "Bratislava",
  "velkost": "trzby 652 tis EUR (2024), 5-9 zam",
  "tel": "0948 083 707",
  "email": "mirka.habudova@gurmanservis.sk",
  "web": "macomenu.sk",
  "zona": "Z2",
  "pozn": "denny rozvoz obedov od 7,50 EUR, dovoz zdarma, min 2 ks",
  "lat": 48.1794915,
  "lon": 17.1664571
 },
 {
  "kat": "Catering dodavatel",
  "firma": "Manna Factory s.r.o.",
  "ico": "52941051",
  "adresa": "Latoricka 4",
  "mesto": "Bratislava-Podunajske Biskupice",
  "okres": "Bratislava",
  "velkost": "trzby ~1,0 mil EUR (2025), 25-49 zam",
  "tel": "0902 985 500",
  "email": "office@mannacatering.sk",
  "web": "mannacatering.sk",
  "zona": "Z5",
  "pozn": "SILNY CIEL; korporatne eventy (Accenture, IBM, Microsoft)",
  "lat": 48.1345931,
  "lon": 17.2114238
 },
 {
  "kat": "Catering dodavatel",
  "firma": "CATERINGOVE SLUZBY s.r.o. (123Catering)",
  "ico": "44745982",
  "adresa": "Cernysevskeho 10",
  "mesto": "Bratislava-Petrzalka",
  "okres": "Bratislava",
  "velkost": "trzby 1,3 mil EUR (2025), 5-9 zam",
  "tel": "",
  "email": "",
  "web": "123catering.sk",
  "zona": "Z3",
  "pozn": "event catering; kontakt cez web/ORSR",
  "lat": 48.1281468,
  "lon": 17.1095441
 },
 {
  "kat": "Catering dodavatel",
  "firma": "Smart Business Solutions s.r.o. (AMIS Group)",
  "ico": "47111925",
  "adresa": "Laliova 2792/28",
  "mesto": "Bratislava-Ruzinov",
  "okres": "Bratislava",
  "velkost": "trzby 1,43 mil EUR (2024), 10-19 zam",
  "tel": "+421 910 259 945",
  "email": "manager@amisgroup.sk",
  "web": "amisgroup.sk",
  "zona": "Z2",
  "pozn": "zavodne stravovanie + sala Senec 250 os",
  "lat": 48.144877,
  "lon": 17.1749469
 },
 {
  "kat": "Catering dodavatel",
  "firma": "Soupa s.r.o.",
  "ico": "43814336",
  "adresa": "Kozia 11",
  "mesto": "Bratislava-Stare Mesto",
  "okres": "Bratislava",
  "velkost": "trzby 1,53 mil EUR (2024), 10-19 zam",
  "tel": "0948 611 544",
  "email": "info@soupa.sk",
  "web": "soupa.sk",
  "zona": "Z1",
  "pozn": "bufety, ranajky, priestor Kulturama do 200 os",
  "lat": 48.1463945,
  "lon": 17.1029415
 },
 {
  "kat": "Catering dodavatel",
  "firma": "ROXY CATERING s.r.o.",
  "ico": "36701661",
  "adresa": "Bajkalska 29/E",
  "mesto": "Bratislava-Ruzinov",
  "okres": "Bratislava",
  "velkost": "trzby 3,12 mil EUR (2024), 25-49 zam",
  "tel": "+421 903 456 662",
  "email": "",
  "web": "roxycatering.sk",
  "zona": "Z2",
  "pozn": "recepcie, vecierky, plesy",
  "lat": 48.1513206,
  "lon": 17.150143
 },
 {
  "kat": "Catering dodavatel",
  "firma": "PAPA GRILL s.r.o. (+ Royal Catering)",
  "ico": "45689679",
  "adresa": "Priemyselna 5863",
  "mesto": "Malacky",
  "okres": "Malacky",
  "velkost": "trzby 4,85 mil EUR (2025), 25-49 zam",
  "tel": "+421 910 333 511",
  "email": "info@papagrill.sk",
  "web": "papagrill.sk",
  "zona": "Z6",
  "pozn": "SILNY CIEL; kontraktove firemne jedalne, kuchyna 600 m2; event +421 911 580 480",
  "lat": 48.4213126,
  "lon": 17.0373725
 },
 {
  "kat": "Catering dodavatel",
  "firma": "CITY GASTRO a.s.",
  "ico": "46323279",
  "adresa": "Sliacska 3269/1E",
  "mesto": "Bratislava-Nove Mesto",
  "okres": "Bratislava",
  "velkost": "trzby 8,33 mil EUR (2024), 100-149 zam",
  "tel": "+421 948 929 323",
  "email": "sekretariat@citygastro.sk",
  "web": "citygastro.sk",
  "zona": "Z2",
  "pozn": "zavodne stravovanie + catering, ISO 9001/22000; prevadzkuje jedalen EUBA",
  "lat": 48.1714307,
  "lon": 17.1245613
 },
 {
  "kat": "Catering dodavatel",
  "firma": "ALDENTE s.r.o. (Bencik Culinary Group)",
  "ico": "35882841",
  "adresa": "Hviezdoslavovo nam. 20",
  "mesto": "Bratislava-Stare Mesto",
  "okres": "Bratislava",
  "velkost": "trzby 8,52 mil EUR (2024), 150-199 zam",
  "tel": "",
  "email": "info@bencikculinary.sk",
  "web": "bencikculinary.sk",
  "zona": "Z1",
  "pozn": "premiove jedalne v BC (Obederia, La Cantina)",
  "lat": 48.1421185,
  "lon": 17.1078921
 },
 {
  "kat": "Catering dodavatel",
  "firma": "Medusa Restaurants a.s. (Medusa Catering)",
  "ico": "35849592",
  "adresa": "Sutazna 3",
  "mesto": "Bratislava-Ruzinov",
  "okres": "Bratislava",
  "velkost": "trzby 28,76 mil EUR (2024), 250-499 zam",
  "tel": "+421 2 3300 2808",
  "email": "",
  "web": "medusarestaurants.sk",
  "zona": "Z2",
  "pozn": "najvacsia gastro skupina SK; event catering pre tisice",
  "lat": 48.1488728,
  "lon": 17.1273748
 },
 {
  "kat": "Catering dodavatel",
  "firma": "SKGastro",
  "ico": "doplnit ORSR",
  "adresa": "doplnit",
  "mesto": "Bratislava",
  "okres": "Bratislava",
  "velkost": "nezverejnene",
  "tel": "0908 898 677",
  "email": "skgastro@skgastro.sk",
  "web": "skgastro.sk",
  "zona": "Z?",
  "pozn": "zavodne stravovanie; over ICO + sidlo",
  "lat": 48.1516988,
  "lon": 17.1093063
 },
 {
  "kat": "Catering dodavatel",
  "firma": "Catering Bratislava",
  "ico": "doplnit ORSR",
  "adresa": "Galvaniho 12/B",
  "mesto": "Bratislava-Ruzinov",
  "okres": "Bratislava",
  "velkost": "nezverejnene",
  "tel": "0910 166 999",
  "email": "catering@cateringbratislava.sk",
  "web": "cateringbratislava.sk",
  "zona": "Z2",
  "pozn": "eventy + pozicovna inventara; over ICO",
  "lat": 48.1738535,
  "lon": 17.176006
 },
 {
  "kat": "Catering dodavatel",
  "firma": "GASTRO-CENTRUM Antovszky s.r.o.",
  "ico": "31402666",
  "adresa": "Hradska 26",
  "mesto": "Bratislava-Vrakuna",
  "okres": "Bratislava",
  "velkost": "spiaca firma ~0 EUR",
  "tel": "",
  "email": "",
  "web": "antovszkycatering.sk",
  "zona": "Z5",
  "pozn": "VYRADIT - fakticky necinna",
  "lat": 48.1520531,
  "lon": 17.1987878
 },
 {
  "kat": "Vyvaren / catering kuchyna",
  "firma": "Delirest Slovakia s.r.o. (brand EUREST)",
  "ico": "31342809",
  "adresa": "Plynarenska 7/B",
  "mesto": "Bratislava-Ruzinov",
  "okres": "Bratislava",
  "velkost": "LIDER: 35,5 mil EUR, 500-999 zam",
  "tel": "",
  "email": "",
  "web": "eurest.sk",
  "zona": "Z2",
  "pozn": "tel/email cez ORSR (web docasne down)",
  "lat": 48.1455454,
  "lon": 17.143422
 },
 {
  "kat": "Vyvaren / catering kuchyna",
  "firma": "FOOD TIME s.r.o.",
  "ico": "52079881",
  "adresa": "Lozorno 995 (prevadzka)",
  "mesto": "Lozorno",
  "okres": "Malacky",
  "velkost": "~5,2 mil EUR (2023); 10000+ porcii/den",
  "tel": "+421 918 797 063",
  "email": "obchod@food-time.sk",
  "web": "food-time.sk",
  "zona": "Z6",
  "pozn": "najvyssia kapacita; sidlo Tren. Teplice, prevadzka v BA kraji",
  "lat": 48.3346371,
  "lon": 17.0444471
 },
 {
  "kat": "Vyvaren / catering kuchyna",
  "firma": "GTH catering s.r.o. (ex-Sodexo)",
  "ico": "35728434",
  "adresa": "Vajnorska 100/B",
  "mesto": "Bratislava-Nove Mesto",
  "okres": "Bratislava",
  "velkost": "7,1 mil EUR, 150-199 zam",
  "tel": "",
  "email": "",
  "web": "gthcatering.sk",
  "zona": "Z2",
  "pozn": "sidlo sa stahuje do Nitry od 1.6.2026",
  "lat": 48.1698902,
  "lon": 17.140156
 },
 {
  "kat": "Vyvaren / catering kuchyna",
  "firma": "SHARKAM B&B Catering s.r.o.",
  "ico": "46844341",
  "adresa": "Krokusova 3 (kanc. Technopol, Kutlikova 17)",
  "mesto": "Bratislava-Petrzalka",
  "okres": "Bratislava",
  "velkost": "3,4 mil EUR; jedalen 850 ludi/den",
  "tel": "+421 915 763 073",
  "email": "bankovich@sharkam.eu",
  "web": "sharkam.eu",
  "zona": "Z3",
  "pozn": "jedalen Technopol + protokolarny catering",
  "lat": 48.1352541,
  "lon": 17.1152978
 },
 {
  "kat": "Vyvaren / catering kuchyna",
  "firma": "RC Slovakia s.r.o. (SKIES Catering)",
  "ico": "35870362",
  "adresa": "Vajnorska 100/B",
  "mesto": "Bratislava-Nove Mesto",
  "okres": "Bratislava",
  "velkost": "1,2 mil EUR; ISO/IFS/BRC",
  "tel": "+421 911 713 000",
  "email": "javorkova@rcslovakia.sk",
  "web": "rcslovakia.sk",
  "zona": "Z2",
  "pozn": "eventy, kongresy",
  "lat": 48.1698902,
  "lon": 17.140156
 },
 {
  "kat": "Vyvaren / catering kuchyna",
  "firma": "Timeout Catering s.r.o.",
  "ico": "55083561",
  "adresa": "Polna 4",
  "mesto": "Senec",
  "okres": "Senec",
  "velkost": "event do 1000 ludi",
  "tel": "+421 918 227 782",
  "email": "info@timeoutcatering.sk",
  "web": "timeoutcatering.sk",
  "zona": "Z8",
  "pozn": "pokryva BA + Senec + Pezinok",
  "lat": 48.2086452,
  "lon": 17.4018888
 },
 {
  "kat": "Vyvaren / catering kuchyna",
  "firma": "PINO group s.r.o.",
  "ico": "44013141",
  "adresa": "Kadnarova 99",
  "mesto": "Bratislava-Raca",
  "okres": "Bratislava",
  "velkost": "skolske + firemne jedalne",
  "tel": "+421 904 884 427",
  "email": "objednavky@pinostravovanie.sk",
  "web": "pinostravovanie.sk",
  "zona": "Z2",
  "pozn": "17+ rokov",
  "lat": 48.2053369,
  "lon": 17.1465294
 },
 {
  "kat": "Vyvaren / catering kuchyna",
  "firma": "Oldeji (J. Cerna Szalay, zivnost)",
  "ico": "32212721",
  "adresa": "Rusovska cesta 3903/50",
  "mesto": "Bratislava-Petrzalka",
  "okres": "Bratislava",
  "velkost": "vlastna kuchyna od 1994, 10-19 zam",
  "tel": "0904 630 487",
  "email": "info@oldeji.sk",
  "web": "oldeji.sk",
  "zona": "Z3",
  "pozn": "rozvoz v termonadobach + prevadzka jedalni",
  "lat": 48.1235338,
  "lon": 17.1089883
 },
 {
  "kat": "Vyvaren / catering kuchyna",
  "firma": "ALFA FOOD vzs s.r.o.",
  "ico": "55167071",
  "adresa": "Zilinska 7028/1",
  "mesto": "Bratislava-Stare Mesto",
  "okres": "Bratislava",
  "velkost": "0,62 mil EUR (2024), 25-49 zam",
  "tel": "+421 903 995 595",
  "email": "info@alfafood.sk",
  "web": "alfafood.sk",
  "zona": "Z1",
  "pozn": "zavodne stravovanie",
  "lat": 48.1545738,
  "lon": 17.1112842
 },
 {
  "kat": "Vyvaren / catering kuchyna",
  "firma": "ProZeta s.r.o. (Happy Day Catering)",
  "ico": "36739499",
  "adresa": "Padlych hrdinov 24",
  "mesto": "Bratislava-Podunajske Biskupice",
  "okres": "Bratislava",
  "velkost": "svadby, eventy, firmy",
  "tel": "0948 080 180",
  "email": "info@happy-day.sk",
  "web": "happydaycatering.sk",
  "zona": "Z5",
  "pozn": "16+ rokov",
  "lat": 48.1237261,
  "lon": 17.2123351
 },
 {
  "kat": "Vyvaren / catering kuchyna",
  "firma": "TOVAR a SLUZBY s.r.o. (Jedlo Bratislava)",
  "ico": "51725053",
  "adresa": "Popovova 8 (kuchyna Dr. V. Clementisa 5)",
  "mesto": "Bratislava-Ruzinov",
  "okres": "Bratislava",
  "velkost": "rozvoz obedov",
  "tel": "0905 600 000",
  "email": "",
  "web": "jedlobratislava.sk",
  "zona": "Z2",
  "pozn": "rozvoz po celej BA vratane noci",
  "lat": 48.1608571,
  "lon": 17.1477295
 },
 {
  "kat": "Vyvaren / catering kuchyna",
  "firma": "OXA Delivery Service s.r.o.",
  "ico": "50293231",
  "adresa": "Stredna 1",
  "mesto": "Bratislava-Ruzinov",
  "okres": "Bratislava",
  "velkost": "0,6 mil EUR (2024), 5-9 zam",
  "tel": "",
  "email": "",
  "web": "",
  "zona": "Z2",
  "pozn": "catering pre materske skoly; kontakt cez ORSR",
  "lat": 48.1763819,
  "lon": 17.1703672
 },
 {
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Eat & Meet - Mlynska dolina (UK)",
  "ico": "",
  "adresa": "Stare Grunty, blok AD-U, Mlynska dolina",
  "mesto": "Bratislava-Karlova Ves",
  "okres": "Bratislava",
  "velkost": "450 miest, 4000+ jedal/den (areal Mlyny az 6000)",
  "tel": "",
  "email": "",
  "web": "eatandmeet.sk",
  "zona": "Z4",
  "pozn": "univerzitna; vlastna prevadzka UK",
  "lat": 48.1641859,
  "lon": 17.0678683
 },
 {
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Venza - Mlyny UK",
  "ico": "",
  "adresa": "Mlynska dolina",
  "mesto": "Bratislava-Karlova Ves",
  "okres": "Bratislava",
  "velkost": "sucast arealu Mlyny (6000/den)",
  "tel": "",
  "email": "",
  "web": "mlyny.uniba.sk",
  "zona": "Z4",
  "pozn": "univerzitna jedalen",
  "lat": 48.1548435,
  "lon": 17.06991
 },
 {
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Jedalen EUBA - Dolnozemska (City Gastro)",
  "ico": "",
  "adresa": "Dolnozemska cesta 1",
  "mesto": "Bratislava-Petrzalka",
  "okres": "Bratislava",
  "velkost": "500 miest / 1500 pri recepcii",
  "tel": "+421 948 929 323",
  "email": "sekretariat@citygastro.sk",
  "web": "citygastro.sk",
  "zona": "Z3",
  "pozn": "prevadzkuje City Gastro",
  "lat": 48.1275493,
  "lon": 17.1323468
 },
 {
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Jedalen Mlada garda (STU)",
  "ico": "",
  "adresa": "Racianska 103",
  "mesto": "Bratislava-Nove Mesto",
  "okres": "Bratislava",
  "velkost": "136 miest + siet 5-7 jedalni STU",
  "tel": "+421 918 600 162",
  "email": "",
  "web": "stuba.sk",
  "zona": "Z2",
  "pozn": "UZ SDaJ STU",
  "lat": 48.177312,
  "lon": 17.1261017
 },
 {
  "kat": "Tackaren / zavodna jedalen",
  "firma": "UNB - Nemocnica Ruzinov",
  "ico": "",
  "adresa": "Ruzinovska 6",
  "mesto": "Bratislava-Ruzinov",
  "okres": "Bratislava",
  "velkost": ">100k hospitalizacii/rok",
  "tel": "02 48234111",
  "email": "",
  "web": "unb.sk",
  "zona": "Z2",
  "pozn": "vlastna OLVaS; vstup cez verejne obstaravanie",
  "lat": 48.1552301,
  "lon": 17.1519477
 },
 {
  "kat": "Tackaren / zavodna jedalen",
  "firma": "UNB - Nem. ak. L. Derera (Kramare)",
  "ico": "",
  "adresa": "Limbova 5",
  "mesto": "Bratislava-Nove Mesto",
  "okres": "Bratislava",
  "velkost": "velka nemocnica",
  "tel": "",
  "email": "",
  "web": "unb.sk",
  "zona": "Z2",
  "pozn": "vlastna kuchyna, tacovy system",
  "lat": 48.1662606,
  "lon": 17.0863257
 },
 {
  "kat": "Tackaren / zavodna jedalen",
  "firma": "UNB - Nem. sv. Cyrila a Metoda (Petrzalka)",
  "ico": "",
  "adresa": "Antolska 11",
  "mesto": "Bratislava-Petrzalka",
  "okres": "Bratislava",
  "velkost": "velka nemocnica",
  "tel": "",
  "email": "",
  "web": "unb.sk",
  "zona": "Z3",
  "pozn": "vlastna kuchyna",
  "lat": 48.1020874,
  "lon": 17.1183618
 },
 {
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Narodny ustav srdc. a cievnych chorob (NUSCH)",
  "ico": "",
  "adresa": "Pod Krasnou horkou 1",
  "mesto": "Bratislava-Kramare",
  "okres": "Bratislava",
  "velkost": "vlastna kuchyna",
  "tel": "",
  "email": "",
  "web": "nusch.sk",
  "zona": "Z2",
  "pozn": "",
  "lat": 48.1696588,
  "lon": 17.0869479
 },
 {
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Narodny onkologicky ustav (NOU)",
  "ico": "",
  "adresa": "Klenova 1",
  "mesto": "Bratislava-Kramare",
  "okres": "Bratislava",
  "velkost": "vlastna kuchyna, ~200+ lozok",
  "tel": "",
  "email": "",
  "web": "nou.sk",
  "zona": "Z2",
  "pozn": "",
  "lat": 48.1718244,
  "lon": 17.0894784
 },
 {
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Nemocnica sv. Michala",
  "ico": "",
  "adresa": "Satinskeho I. 1",
  "mesto": "Bratislava-Stare Mesto",
  "okres": "Bratislava",
  "velkost": "vlastna OLVaS",
  "tel": "",
  "email": "",
  "web": "nsmas.sk",
  "zona": "Z1",
  "pozn": "vojensko-policajna univ. nemocnica",
  "lat": 48.1452492,
  "lon": 17.1175227
 },
 {
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Volkswagen Slovakia - zavodna jedalen",
  "ico": "",
  "adresa": "Jana Jonasa 1",
  "mesto": "Bratislava-Devinska Nova Ves",
  "okres": "Bratislava",
  "velkost": "NAJVACSI CIEL: ~11-13 tis. zamestnancov",
  "tel": "",
  "email": "facility/HR",
  "web": "volkswagen.sk",
  "zona": "Z4",
  "pozn": "operator stravovania NEOVERENY - priamy dopyt",
  "lat": 48.2350546,
  "lon": 16.9817538
 },
 {
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Slovnaft - zavodna jedalen",
  "ico": "",
  "adresa": "Vlcie hrdlo 1",
  "mesto": "Bratislava-Ruzinov",
  "okres": "Bratislava",
  "velkost": "velky priemyselny zavod",
  "tel": "",
  "email": "facility",
  "web": "slovnaft.sk",
  "zona": "Z5",
  "pozn": "operator neovereny",
  "lat": 48.1282386,
  "lon": 17.176661
 },
 {
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Mondelez SR Production - kantina",
  "ico": "",
  "adresa": "Racianska 44",
  "mesto": "Bratislava-Raca",
  "okres": "Bratislava",
  "velkost": "~400 zamestnancov",
  "tel": "",
  "email": "",
  "web": "",
  "zona": "Z2",
  "pozn": "cokoladovna",
  "lat": 48.1932309,
  "lon": 17.1416428
 },
 {
  "kat": "Tackaren / zavodna jedalen",
  "firma": "La Cantina - Tatracentrum (Bencik)",
  "ico": "",
  "adresa": "Hodzovo nam. 3",
  "mesto": "Bratislava-Stare Mesto",
  "okres": "Bratislava",
  "velkost": "BC kantina",
  "tel": "",
  "email": "",
  "web": "bencikculinary.sk",
  "zona": "Z1",
  "pozn": "siet kantin v BC (Central, Apollo, Petrzalka)",
  "lat": 48.1484131,
  "lon": 17.1087896
 },
 {
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Food Season - Westend Square",
  "ico": "",
  "adresa": "Dubravska cesta 2",
  "mesto": "Bratislava-Karlova Ves",
  "okres": "Bratislava",
  "velkost": "firemna kantina",
  "tel": "",
  "email": "",
  "web": "foodseason.sk",
  "zona": "Z4",
  "pozn": "bio suroviny, sous-vide",
  "lat": 48.1686969,
  "lon": 17.0753887
 },
 {
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Canteen Priatelia - Westend Tower",
  "ico": "",
  "adresa": "Dubravska cesta 2",
  "mesto": "Bratislava-Karlova Ves",
  "okres": "Bratislava",
  "velkost": "firemna kantina",
  "tel": "",
  "email": "",
  "web": "",
  "zona": "Z4",
  "pozn": "",
  "lat": 48.1686969,
  "lon": 17.0753887
 },
 {
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Fajne Jedlo - Tower 115",
  "ico": "",
  "adresa": "Pribinova 25",
  "mesto": "Bratislava-Stare Mesto",
  "okres": "Bratislava",
  "velkost": "samoobsluzna kantina",
  "tel": "",
  "email": "",
  "web": "",
  "zona": "Z1",
  "pozn": "zona Eurovea/Twin City",
  "lat": 48.1411404,
  "lon": 17.1273381
 },
 {
  "kat": "Velka restauracia / banketova sala",
  "firma": "Zylinder Cafe & Restaurant",
  "ico": "",
  "adresa": "Hviezdoslavovo nam. 19",
  "mesto": "Bratislava-Stare Mesto",
  "okres": "Bratislava",
  "velkost": "80 sed / 120 raut + terasa 50",
  "tel": "+421 903 123 134",
  "email": "rezervacie@zylinder.sk",
  "web": "zylinder.sk",
  "zona": "Z1",
  "pozn": "",
  "lat": 48.1419314,
  "lon": 17.1077327
 },
 {
  "kat": "Velka restauracia / banketova sala",
  "firma": "Restauracia Matysak (Vinny hotel)",
  "ico": "",
  "adresa": "Holubyho 85",
  "mesto": "Pezinok",
  "okres": "Pezinok",
  "velkost": "130 + terasa 30, banketove priestory",
  "tel": "0907 701 070",
  "email": "restauracia@vinomatysak.sk",
  "web": "restauraciamatysak.sk",
  "zona": "Z7",
  "pozn": "svadby",
  "lat": 48.2883571,
  "lon": 17.2666299
 },
 {
  "kat": "Velka restauracia / banketova sala",
  "firma": "Bratislavsky mestiansky pivovar - Drevena",
  "ico": "",
  "adresa": "Drevena 8",
  "mesto": "Bratislava-Stare Mesto",
  "okres": "Bratislava",
  "velkost": "~180 + terasa 25, salonik 35",
  "tel": "",
  "email": "info@mestianskypivovar.sk",
  "web": "mestianskypivovar.sk",
  "zona": "Z1",
  "pozn": "",
  "lat": 48.1469194,
  "lon": 17.1081791
 },
 {
  "kat": "Velka restauracia / banketova sala",
  "firma": "Event Hall Malacky",
  "ico": "",
  "adresa": "Malacky",
  "mesto": "Malacky",
  "okres": "Malacky",
  "velkost": "svadobna sala do 250, vlastna kuchyna",
  "tel": "",
  "email": "",
  "web": "eventhall.sk",
  "zona": "Z6",
  "pozn": "kontakt cez web",
  "lat": 48.4325413,
  "lon": 17.0230915
 },
 {
  "kat": "Velka restauracia / banketova sala",
  "firma": "Bratislavsky mestiansky pivovar - Dunajska",
  "ico": "",
  "adresa": "Dunajska 21",
  "mesto": "Bratislava-Stare Mesto",
  "okres": "Bratislava",
  "velkost": "~280 + terasa 300, salonik 60",
  "tel": "0948 710 888",
  "email": "dunajska@mestianskypivovar.sk",
  "web": "mestianskypivovar.sk",
  "zona": "Z1",
  "pozn": "",
  "lat": 48.1459308,
  "lon": 17.1176901
 },
 {
  "kat": "Velka restauracia / banketova sala",
  "firma": "ELESKO Wine Park (Restaurant & Wine bar)",
  "ico": "",
  "adresa": "Partizanska 2275",
  "mesto": "Modra",
  "okres": "Pezinok",
  "velkost": "Zoya Museum 200-400, restauracia 80",
  "tel": "+421 905 704 873",
  "email": "",
  "web": "elesko.sk",
  "zona": "Z7",
  "pozn": "event manager Peter Toth",
  "lat": 48.3541412,
  "lon": 17.3219993
 },
 {
  "kat": "Velka restauracia / banketova sala",
  "firma": "Slovak Pub",
  "ico": "",
  "adresa": "Obchodna 62",
  "mesto": "Bratislava-Stare Mesto",
  "okres": "Bratislava",
  "velkost": "~500 miest (11 miestnosti)",
  "tel": "+421 917 629 221",
  "email": "slovakpub@slovakpub.sk",
  "web": "slovakpub.sk",
  "zona": "Z1",
  "pozn": "",
  "lat": 48.1483346,
  "lon": 17.1124098
 },
 {
  "kat": "Velka restauracia / banketova sala",
  "firma": "NH Bratislava Gate One",
  "ico": "",
  "adresa": "Ambrusova 7",
  "mesto": "Bratislava-Ruzinov",
  "okres": "Bratislava",
  "velkost": "najvacsia sala do 600, 8-10 sal",
  "tel": "",
  "email": "nhgateone@nh-hotels.com",
  "web": "nh-hotels.com",
  "zona": "Z2",
  "pozn": "",
  "lat": 48.1662442,
  "lon": 17.1774457
 },
 {
  "kat": "Velka restauracia / banketova sala",
  "firma": "Holiday Inn Bratislava",
  "ico": "",
  "adresa": "Bajkalska 25/A",
  "mesto": "Bratislava-Ruzinov",
  "okres": "Bratislava",
  "velkost": "6 sal, do 600 hosti",
  "tel": "",
  "email": "",
  "web": "ihg.com",
  "zona": "Z2",
  "pozn": "event kontakt cez IHG",
  "lat": 48.1530346,
  "lon": 17.1488827
 },
 {
  "kat": "Velka restauracia / banketova sala",
  "firma": "Dunajsky pivovar (lod/botel)",
  "ico": "",
  "adresa": "Tyrsovo nabrezie",
  "mesto": "Bratislava-Petrzalka",
  "okres": "Bratislava",
  "velkost": "~600 (terasa 250, salonik 50)",
  "tel": "+421 948 418 934",
  "email": "dunajskypivovar@dunajskypivovar.sk",
  "web": "dunajskypivovar.sk",
  "zona": "Z3",
  "pozn": "",
  "lat": 48.1363762,
  "lon": 17.1132834
 },
 {
  "kat": "Velka restauracia / banketova sala",
  "firma": "Hotel Saffron",
  "ico": "",
  "adresa": "Radlinskeho 27",
  "mesto": "Bratislava-Stare Mesto",
  "okres": "Bratislava",
  "velkost": "6 sal, 1500 m2, do 900 osob",
  "tel": "+421 948 660 459",
  "email": "marketing@hotelsaffron.sk",
  "web": "hotelsaffron.sk",
  "zona": "Z1",
  "pozn": "",
  "lat": 48.1523448,
  "lon": 17.117072
 },
 {
  "kat": "Velka restauracia / banketova sala",
  "firma": "Radisson Blu Carlton",
  "ico": "",
  "adresa": "Hviezdoslavovo nam. 3",
  "mesto": "Bratislava-Stare Mesto",
  "okres": "Bratislava",
  "velkost": "do 1000 hosti",
  "tel": "+421 2 5939 0000",
  "email": "reservation.bratislava@radissonblu.com",
  "web": "radissonhotels.com",
  "zona": "Z1",
  "pozn": "",
  "lat": 48.1412124,
  "lon": 17.1085808
 },
 {
  "kat": "Velka restauracia / banketova sala",
  "firma": "Hotel Senec (Lake & Aqua Resort)",
  "ico": "",
  "adresa": "Slnecne jazera-Sever",
  "mesto": "Senec",
  "okres": "Senec",
  "velkost": "kongres do 1000 (svadby do ~300)",
  "tel": "+421 904 543 513",
  "email": "kakasova@hotelsenec.sk",
  "web": "hotelsenec.sk",
  "zona": "Z8",
  "pozn": "event Stela Kakasova",
  "lat": 48.2215028,
  "lon": 17.4005824
 },
 {
  "kat": "Velka restauracia / banketova sala",
  "firma": "Sheraton Bratislava",
  "ico": "",
  "adresa": "Pribinova 12",
  "mesto": "Bratislava-Stare Mesto",
  "okres": "Bratislava",
  "velkost": "ballroom do 400, standing do 1500",
  "tel": "",
  "email": "",
  "web": "marriott.com",
  "zona": "Z1",
  "pozn": "Eurovea; event cez Marriott MICE",
  "lat": 48.1403976,
  "lon": 17.1223178
 },
 {
  "kat": "Velka restauracia / banketova sala",
  "firma": "Park Inn by Radisson Danube",
  "ico": "",
  "adresa": "Rybne nam. 1",
  "mesto": "Bratislava-Stare Mesto",
  "okres": "Bratislava",
  "velkost": "event 471 m2, do 400 delegatov",
  "tel": "",
  "email": "",
  "web": "radissonhotels.com",
  "zona": "Z1",
  "pozn": "",
  "lat": 48.1404872,
  "lon": 17.1050761
 },
 {
  "kat": "Velka restauracia / banketova sala",
  "firma": "Falkensteiner Hotel Bratislava",
  "ico": "",
  "adresa": "Pilarikova 5",
  "mesto": "Bratislava-Stare Mesto",
  "okres": "Bratislava",
  "velkost": "sala 173 m2, recepcia do 300",
  "tel": "+421 2 5923 6100",
  "email": "",
  "web": "falkensteiner.com",
  "zona": "Z1",
  "pozn": "",
  "lat": 48.1460616,
  "lon": 17.1034683
 },
 {
  "kat": "Velka restauracia / banketova sala",
  "firma": "Grand Hotel River Park (Luxury Collection)",
  "ico": "",
  "adresa": "Dvorakovo nabrezie 6",
  "mesto": "Bratislava-Stare Mesto",
  "okres": "Bratislava",
  "velkost": "banketove saly",
  "tel": "",
  "email": "",
  "web": "grandriverpark.sk",
  "zona": "Z1",
  "pozn": "event cez Marriott",
  "lat": 48.1414165,
  "lon": 17.0903098
 },
 {
  "kat": "Velka restauracia / banketova sala",
  "firma": "Koliba Senec",
  "ico": "",
  "adresa": "Slnecne jazera-Sever",
  "mesto": "Senec",
  "okres": "Senec",
  "velkost": "svadby/oslavy/firemne, bazen, ubytovanie",
  "tel": "+421 908 602 020",
  "email": "",
  "web": "kolibasenec.sk",
  "zona": "Z8",
  "pozn": "",
  "lat": 48.2215028,
  "lon": 17.4005824
 },
 {
  "kat": "Velka restauracia / banketova sala",
  "firma": "Stara trznica",
  "ico": "",
  "adresa": "Namestie SNP 25",
  "mesto": "Bratislava-Stare Mesto",
  "okres": "Bratislava",
  "velkost": "multifunkcna hala, velke eventy",
  "tel": "+421 948 420 999",
  "email": "trznica@staratrznica.sk",
  "web": "staratrznica.sk",
  "zona": "Z1",
  "pozn": "catering externy",
  "lat": 48.1448115,
  "lon": 17.1112785
 },
 {
  "kat": "Velka restauracia / banketova sala",
  "firma": "Restauracia Zeleny dvor",
  "ico": "",
  "adresa": "M. R. Stefanika 110",
  "mesto": "Malacky",
  "okres": "Malacky",
  "velkost": "svadby/oslavy/firemne",
  "tel": "+421 917 977 311",
  "email": "",
  "web": "zelenydvormalacky.sk",
  "zona": "Z6",
  "pozn": "",
  "lat": 48.425248,
  "lon": 17.0201504
 },
 {
  "kat": "Velka restauracia / banketova sala",
  "firma": "Penzion Palenica",
  "ico": "",
  "adresa": "Bernolakovo",
  "mesto": "Bernolakovo",
  "okres": "Senec",
  "velkost": "terasova miestnost ~100, restauracia 60",
  "tel": "",
  "email": "",
  "web": "penzionpalenica.eu",
  "zona": "Z8",
  "pozn": "",
  "lat": 48.1989817,
  "lon": 17.3000328
 },
 {
  "kat": "Velka restauracia / banketova sala",
  "firma": "RIVERBANK Restaurant",
  "ico": "",
  "adresa": "Dvorakovo nabrezie",
  "mesto": "Bratislava-Stare Mesto",
  "okres": "Bratislava",
  "velkost": "fine-dining pri Dunaji",
  "tel": "+421 910 872 168",
  "email": "",
  "web": "riverbank.sk",
  "zona": "Z1",
  "pozn": "pri Grand Hotel River Park",
  "lat": 48.1437502,
  "lon": 17.0755555
 },
 {
  "kat": "Velka restauracia / banketova sala",
  "firma": "Hotel Nostalgia",
  "ico": "",
  "adresa": "Senec",
  "mesto": "Senec",
  "okres": "Senec",
  "velkost": "sala do ~120 s parketom",
  "tel": "",
  "email": "",
  "web": "hotelnostalgia.sk",
  "zona": "Z8",
  "pozn": "svadby/oslavy",
  "lat": 48.2199473,
  "lon": 17.3969901
 },
 {
  "kat": "Restauracna siet (3+ prevadzok)",
  "firma": "KRUH remeselna pekaren (Kruh remeselna vyroba s.r.o.)",
  "ico": "47762799",
  "adresa": "Kutuzovova 11 (sidlo)",
  "mesto": "Bratislava-Nove Mesto",
  "okres": "Bratislava",
  "velkost": "3 prevadzky",
  "tel": "+421 915 512 230",
  "email": "ahoj@kruhpekaren.sk",
  "web": "kruhpekaren.sk",
  "zona": "Z2",
  "pozn": "Vajnorska 21, Florianska 16, Zilinska 2",
  "lat": 48.1647644,
  "lon": 17.1307846
 },
 {
  "kat": "Restauracna siet (3+ prevadzok)",
  "firma": "Triple Five Coffee",
  "ico": "47117311",
  "adresa": "Jozefska 2A",
  "mesto": "Bratislava-Stare Mesto",
  "okres": "Bratislava",
  "velkost": "3 prevadzky",
  "tel": "0940 629 026",
  "email": "",
  "web": "triplefivecoffee.com",
  "zona": "Z1",
  "pozn": "Jozefska, Turbinova, Racianska",
  "lat": 48.1509638,
  "lon": 17.1096081
 },
 {
  "kat": "Restauracna siet (3+ prevadzok)",
  "firma": "Fresh Garden Salads (FRESH GARDEN s.r.o.)",
  "ico": "45522464",
  "adresa": "Plynarenska 2/A",
  "mesto": "Bratislava-Ruzinov",
  "okres": "Bratislava",
  "velkost": "3 prevadzky",
  "tel": "+421 902 311 331",
  "email": "info@freshgarden.sk",
  "web": "freshgarden.sk",
  "zona": "Z2",
  "pozn": "Plynarenska, Digital Park, River Park",
  "lat": 48.1462765,
  "lon": 17.1419155
 },
 {
  "kat": "Restauracna siet (3+ prevadzok)",
  "firma": "Pulitzer family (RIVAS s.r.o.)",
  "ico": "35946008",
  "adresa": "Drobneho 21 (sidlo)",
  "mesto": "Bratislava-Dubravka",
  "okres": "Bratislava",
  "velkost": "3 restauracie fine-dining",
  "tel": "",
  "email": "",
  "web": "",
  "zona": "Z4",
  "pozn": "Stefanka, Pulitzer, U zlateho jelena",
  "lat": 48.1914663,
  "lon": 17.0408338
 },
 {
  "kat": "Restauracna siet (3+ prevadzok)",
  "firma": "Domino's Pizza (APIM Gastro s.r.o.)",
  "ico": "50616951",
  "adresa": "Sartorisova 11 (sidlo)",
  "mesto": "Bratislava-Ruzinov",
  "okres": "Bratislava",
  "velkost": "4 prevadzky",
  "tel": "",
  "email": "",
  "web": "dominospizza.sk",
  "zona": "Z2",
  "pozn": "Krizna, Racianska, Rusovska, Kastielska",
  "lat": 48.1568421,
  "lon": 17.1419539
 },
 {
  "kat": "Restauracna siet (3+ prevadzok)",
  "firma": "EDO-KIN GROUP s.r.o.",
  "ico": "46988882",
  "adresa": "Raztocna 25 (sidlo)",
  "mesto": "Bratislava-Vrakuna",
  "okres": "Bratislava",
  "velkost": "4 prevadzky, trzby 2,84 mil EUR (2024)",
  "tel": "",
  "email": "",
  "web": "",
  "zona": "Z5",
  "pozn": "Central, Blumental, Bory, Cubicon",
  "lat": 48.1491794,
  "lon": 17.2137098
 },
 {
  "kat": "Restauracna siet (3+ prevadzok)",
  "firma": "Coffeeshop Company CEE s.r.o.",
  "ico": "35689498",
  "adresa": "Janoskova 4 (sidlo)",
  "mesto": "Bratislava-Nove Mesto",
  "okres": "Bratislava",
  "velkost": "5-6 kaviarni",
  "tel": "",
  "email": "",
  "web": "coffeeshopcompany.com",
  "zona": "Z2",
  "pozn": "Central, Aupark, Lakeside, Rosum, EUBA",
  "lat": 48.1754477,
  "lon": 17.132832
 },
 {
  "kat": "Restauracna siet (3+ prevadzok)",
  "firma": "Regal Burger s.r.o.",
  "ico": "47581930",
  "adresa": "sidlo Drahovce (prevadzky v BA)",
  "mesto": "Bratislava",
  "okres": "Bratislava",
  "velkost": "5-6 prevadzok",
  "tel": "",
  "email": "info@regalburger.com",
  "web": "regalburger.eu",
  "zona": "Z2",
  "pozn": "Eurovea, Bory, Avion, Nivy, Fresh Market",
  "lat": 48.1516988,
  "lon": 17.1093063
 },
 {
  "kat": "Restauracna siet (3+ prevadzok)",
  "firma": "Bevanda",
  "ico": "doplnit",
  "adresa": "Kubacova 23",
  "mesto": "Bratislava-Raca",
  "okres": "Bratislava",
  "velkost": "6 restauracii",
  "tel": "+421 905 551 705",
  "email": "bevanda@bevanda.sk",
  "web": "bevanda.sk",
  "zona": "Z2",
  "pozn": "River Park, Veranda, Istrochem, Anavi",
  "lat": 48.2117407,
  "lon": 17.153861
 },
 {
  "kat": "Restauracna siet (3+ prevadzok)",
  "firma": "Mondieu (MONDIEU BRATISLAVA s.r.o.)",
  "ico": "47114533",
  "adresa": "Mileticova 1 (sidlo)",
  "mesto": "Bratislava-Ruzinov",
  "okres": "Bratislava",
  "velkost": "7 kaviarni",
  "tel": "",
  "email": "info@mondieu.sk",
  "web": "mondieu.sk",
  "zona": "Z2",
  "pozn": "Eurovea, Bory, Nivy, Hviezdoslavovo, Laurinska",
  "lat": 48.1577489,
  "lon": 17.1310655
 },
 {
  "kat": "Restauracna siet (3+ prevadzok)",
  "firma": "Veg Life s.r.o.",
  "ico": "46880526",
  "adresa": "Dubravska cesta 14 (sidlo)",
  "mesto": "Bratislava-Karlova Ves",
  "okres": "Bratislava",
  "velkost": "8 bistro prevadzok",
  "tel": "0905 295 165",
  "email": "info@veglife.sk",
  "web": "veglife.sk",
  "zona": "Z4",
  "pozn": "cisty 1 kontakt - dobry B2B lead",
  "lat": 48.1710686,
  "lon": 17.0712854
 },
 {
  "kat": "Restauracna siet (3+ prevadzok)",
  "firma": "SPUSTA Kaviaren & Pekaren",
  "ico": "31640826",
  "adresa": "Pifflova 6",
  "mesto": "Bratislava-Petrzalka",
  "okres": "Bratislava",
  "velkost": "17-18 prevadzok (vratane Senec, Pezinok)",
  "tel": "+421 918 689 366",
  "email": "info@spustakaviaren.sk",
  "web": "spustakaviaren.sk",
  "zona": "Z3",
  "pozn": "aj okresy; 2. ICO 35803568",
  "lat": 48.1269838,
  "lon": 17.1081707
 },
 {
  "kat": "Restauracna siet (3+ prevadzok)",
  "firma": "Minit Bakery (MINIT SLOVAKIA spol. s r.o.)",
  "ico": "17053897",
  "adresa": "sidlo Dunajska Streda (prevadzky BA+okresy)",
  "mesto": "Bratislava + okresy",
  "okres": "Bratislava/Malacky/Pezinok/Senec",
  "velkost": "30+ prevadzok, pokrytie vsetkych okresov",
  "tel": "",
  "email": "",
  "web": "minitbakery.sk",
  "zona": "viac",
  "pozn": "Senec 1, Pezinok 2, Malacky 3",
  "lat": 48.1516988,
  "lon": 17.1093063
 },
 {
  "kat": "Restauracna siet (3+ prevadzok)",
  "firma": "AmRest Coffee SK s.r.o. (Starbucks)",
  "ico": "50088971",
  "adresa": "Pajstunska 3 (sidlo)",
  "mesto": "Bratislava-Petrzalka",
  "okres": "Bratislava",
  "velkost": "Starbucks 6-7 + KFC/BK/PizzaHut",
  "tel": "",
  "email": "",
  "web": "starbucksslovakia.sk",
  "zona": "Z3",
  "pozn": "skupina AmRest, viac brandov",
  "lat": 48.1111834,
  "lon": 17.1029997
 },
 {
  "kat": "Restauracna siet (3+ prevadzok)",
  "firma": "Queensway Restaurants Slovakia s.r.o. (KFC + Pizza Hut)",
  "ico": "35852143",
  "adresa": "Pribinova 4, Eurovea Central 1",
  "mesto": "Bratislava-Stare Mesto",
  "okres": "Bratislava",
  "velkost": "~20,5 mil EUR; KFC 7 + Pizza Hut 3",
  "tel": "",
  "email": "",
  "web": "kfcslovakia.sk",
  "zona": "Z1",
  "pozn": "over aktualnu entitu (AmRest)",
  "lat": 48.1534392,
  "lon": 17.1151016
 },
 {
  "kat": "Restauracna siet (3+ prevadzok)",
  "firma": "McDonald's Slovakia spol. s r.o.",
  "ico": "31392229",
  "adresa": "Einsteinova 33",
  "mesto": "Bratislava-Petrzalka",
  "okres": "Bratislava",
  "velkost": "52,45 mil EUR (2024); ~18 prevadzok v kraji",
  "tel": "",
  "email": "",
  "web": "mcdonalds.sk",
  "zona": "Z3",
  "pozn": "NAJVACSI retazec; +Pezinok",
  "lat": 48.1314358,
  "lon": 17.100331
 }
];
