const GASTRO_DATA = [
 {
  "kraj": "BA",
  "kat": "Catering dodavatel",
  "firma": "MENju s.r.o.",
  "ico": "53455339",
  "adresa": "Karpatske nam. 10A",
  "mesto": "Bratislava-Raca",
  "okres": "Bratislava III",
  "velkost": "trzby 169 tis EUR (2025), 3-4 zam",
  "tel": "+421 908 368 968",
  "email": "event@menju.sk",
  "web": "menju.sk",
  "zona": "Z2",
  "pozn": "rozvoz do officu + teambuilding; prevadzka Tomasikova 17",
  "lat": 48.2161175,
  "lon": 17.1654827
 },
 {
  "kraj": "BA",
  "kat": "Catering dodavatel",
  "firma": "TOMIR s.r.o. (MacoMenu)",
  "ico": "47981300",
  "adresa": "Bojnicka 10",
  "mesto": "Bratislava-Nove Mesto",
  "okres": "Bratislava III",
  "velkost": "trzby 652 tis EUR (2024), 5-9 zam",
  "tel": "0948 083 707",
  "email": "mirka.habudova@gurmanservis.sk",
  "web": "macomenu.sk",
  "zona": "Z2",
  "pozn": "denny rozvoz obedov od 7,50 EUR, dovoz zdarma, min 2 ks",
  "lat": 48.1794915,
  "lon": 17.1664571
 },
 {
  "kraj": "BA",
  "kat": "Catering dodavatel",
  "firma": "Manna Factory s.r.o.",
  "ico": "52941051",
  "adresa": "Latoricka 4",
  "mesto": "Bratislava-Podunajske Biskupice",
  "okres": "Bratislava II",
  "velkost": "trzby ~1,0 mil EUR (2025), 25-49 zam",
  "tel": "0902 985 500",
  "email": "office@mannacatering.sk",
  "web": "mannacatering.sk",
  "zona": "Z5",
  "pozn": "SILNY CIEL; korporatne eventy (Accenture, IBM, Microsoft)",
  "lat": 48.1345931,
  "lon": 17.2114238
 },
 {
  "kraj": "BA",
  "kat": "Catering dodavatel",
  "firma": "CATERINGOVE SLUZBY s.r.o. (123Catering)",
  "ico": "44745982",
  "adresa": "Cernysevskeho 10",
  "mesto": "Bratislava-Petrzalka",
  "okres": "Bratislava V",
  "velkost": "trzby 1,3 mil EUR (2025), 5-9 zam",
  "tel": "",
  "email": "",
  "web": "123catering.sk",
  "zona": "Z3",
  "pozn": "event catering; kontakt cez web/ORSR",
  "lat": 48.1281468,
  "lon": 17.1095441
 },
 {
  "kraj": "BA",
  "kat": "Catering dodavatel",
  "firma": "Smart Business Solutions s.r.o. (AMIS Group)",
  "ico": "47111925",
  "adresa": "Laliova 2792/28",
  "mesto": "Bratislava-Ruzinov",
  "okres": "Bratislava II",
  "velkost": "trzby 1,43 mil EUR (2024), 10-19 zam",
  "tel": "+421 910 259 945",
  "email": "manager@amisgroup.sk",
  "web": "amisgroup.sk",
  "zona": "Z2",
  "pozn": "zavodne stravovanie + sala Senec 250 os",
  "lat": 48.144877,
  "lon": 17.1749469
 },
 {
  "kraj": "BA",
  "kat": "Catering dodavatel",
  "firma": "Soupa s.r.o.",
  "ico": "43814336",
  "adresa": "Kozia 11",
  "mesto": "Bratislava-Stare Mesto",
  "okres": "Bratislava I",
  "velkost": "trzby 1,53 mil EUR (2024), 10-19 zam",
  "tel": "0948 611 544",
  "email": "info@soupa.sk",
  "web": "soupa.sk",
  "zona": "Z1",
  "pozn": "bufety, ranajky, priestor Kulturama do 200 os",
  "lat": 48.1463945,
  "lon": 17.1029415
 },
 {
  "kraj": "BA",
  "kat": "Catering dodavatel",
  "firma": "ROXY CATERING s.r.o.",
  "ico": "36701661",
  "adresa": "Bajkalska 29/E",
  "mesto": "Bratislava-Ruzinov",
  "okres": "Bratislava II",
  "velkost": "trzby 3,12 mil EUR (2024), 25-49 zam",
  "tel": "+421 903 456 662",
  "email": "",
  "web": "roxycatering.sk",
  "zona": "Z2",
  "pozn": "recepcie, vecierky, plesy",
  "lat": 48.1513206,
  "lon": 17.150143
 },
 {
  "kraj": "BA",
  "kat": "Catering dodavatel",
  "firma": "PAPA GRILL s.r.o. (+ Royal Catering)",
  "ico": "45689679",
  "adresa": "Priemyselna 5863",
  "mesto": "Malacky",
  "okres": "Malacky",
  "velkost": "trzby 4,85 mil EUR (2025), 25-49 zam",
  "tel": "+421 910 333 511",
  "email": "info@papagrill.sk",
  "web": "papagrill.sk",
  "zona": "Z6",
  "pozn": "SILNY CIEL; kontraktove firemne jedalne, kuchyna 600 m2; event +421 911 580 480",
  "lat": 48.4213126,
  "lon": 17.0373725
 },
 {
  "kraj": "BA",
  "kat": "Catering dodavatel",
  "firma": "CITY GASTRO a.s.",
  "ico": "46323279",
  "adresa": "Sliacska 3269/1E",
  "mesto": "Bratislava-Nove Mesto",
  "okres": "Bratislava III",
  "velkost": "trzby 8,33 mil EUR (2024), 100-149 zam",
  "tel": "+421 948 929 323",
  "email": "sekretariat@citygastro.sk",
  "web": "citygastro.sk",
  "zona": "Z2",
  "pozn": "zavodne stravovanie + catering, ISO 9001/22000; prevadzkuje jedalen EUBA",
  "lat": 48.1714307,
  "lon": 17.1245613
 },
 {
  "kraj": "BA",
  "kat": "Catering dodavatel",
  "firma": "ALDENTE s.r.o. (Bencik Culinary Group)",
  "ico": "35882841",
  "adresa": "Hviezdoslavovo nam. 20",
  "mesto": "Bratislava-Stare Mesto",
  "okres": "Bratislava I",
  "velkost": "trzby 8,52 mil EUR (2024), 150-199 zam",
  "tel": "",
  "email": "info@bencikculinary.sk",
  "web": "bencikculinary.sk",
  "zona": "Z1",
  "pozn": "premiove jedalne v BC (Obederia, La Cantina)",
  "lat": 48.1421185,
  "lon": 17.1078921
 },
 {
  "kraj": "BA",
  "kat": "Catering dodavatel",
  "firma": "Medusa Restaurants a.s. (Medusa Catering)",
  "ico": "35849592",
  "adresa": "Sutazna 3",
  "mesto": "Bratislava-Ruzinov",
  "okres": "Bratislava II",
  "velkost": "trzby 28,15 mil EUR (2024), 250-499 zam",
  "tel": "+421 2 3300 2808",
  "email": "",
  "web": "medusarestaurants.sk",
  "zona": "Z2",
  "pozn": "najvacsia gastro skupina SK; event catering pre tisice",
  "lat": 48.1488728,
  "lon": 17.1273748
 },
 {
  "kraj": "BA",
  "kat": "Catering dodavatel",
  "firma": "SKGastro",
  "ico": "doplnit ORSR",
  "adresa": "doplnit",
  "mesto": "Bratislava",
  "okres": "Bratislava I",
  "velkost": "nezverejnene",
  "tel": "0908 898 677",
  "email": "skgastro@skgastro.sk",
  "web": "skgastro.sk",
  "zona": "Z?",
  "pozn": "zavodne stravovanie; over ICO + sidlo",
  "lat": 48.1516988,
  "lon": 17.1093063
 },
 {
  "kraj": "BA",
  "kat": "Catering dodavatel",
  "firma": "Catering Bratislava",
  "ico": "doplnit ORSR",
  "adresa": "Galvaniho 12/B",
  "mesto": "Bratislava-Ruzinov",
  "okres": "Bratislava II",
  "velkost": "nezverejnene",
  "tel": "0910 166 999",
  "email": "catering@cateringbratislava.sk",
  "web": "cateringbratislava.sk",
  "zona": "Z2",
  "pozn": "eventy + pozicovna inventara; over ICO",
  "lat": 48.1738535,
  "lon": 17.176006
 },
 {
  "kraj": "BA",
  "kat": "Catering dodavatel",
  "firma": "GASTRO-CENTRUM Antovszky s.r.o.",
  "ico": "31402666",
  "adresa": "Hradska 26",
  "mesto": "Bratislava-Vrakuna",
  "okres": "Bratislava II",
  "velkost": "spiaca firma ~0 EUR",
  "tel": "",
  "email": "",
  "web": "antovszkycatering.sk",
  "zona": "Z5",
  "pozn": "VYRADIT - fakticky necinna",
  "lat": 48.1520531,
  "lon": 17.1987878
 },
 {
  "kraj": "BA",
  "kat": "Vyvaren / catering kuchyna",
  "firma": "Delirest Slovakia s.r.o. (brand EUREST)",
  "ico": "31342809",
  "adresa": "Plynarenska 7/B",
  "mesto": "Bratislava-Ruzinov",
  "okres": "Bratislava II",
  "velkost": "LIDER: 35,5 mil EUR, 500-999 zam",
  "tel": "",
  "email": "",
  "web": "eurest.sk",
  "zona": "Z2",
  "pozn": "tel/email cez ORSR (web docasne down)",
  "lat": 48.1455454,
  "lon": 17.143422
 },
 {
  "kraj": "BA",
  "kat": "Vyvaren / catering kuchyna",
  "firma": "FOOD TIME s.r.o.",
  "ico": "52079881",
  "adresa": "Lozorno 995 (prevadzka)",
  "mesto": "Lozorno",
  "okres": "Malacky",
  "velkost": "~5,2 mil EUR (2023); 10000+ porcii/den",
  "tel": "+421 918 797 063",
  "email": "obchod@food-time.sk",
  "web": "food-time.sk",
  "zona": "Z6",
  "pozn": "najvyssia kapacita; sidlo Tren. Teplice, prevadzka v BA kraji",
  "lat": 48.3346371,
  "lon": 17.0444471
 },
 {
  "kraj": "BA",
  "kat": "Vyvaren / catering kuchyna",
  "firma": "GTH catering s.r.o. (ex-Sodexo)",
  "ico": "35728434",
  "adresa": "Vajnorska 100/B",
  "mesto": "Bratislava-Nove Mesto",
  "okres": "Bratislava III",
  "velkost": "7,1 mil EUR, 150-199 zam",
  "tel": "",
  "email": "",
  "web": "gthcatering.sk",
  "zona": "Z2",
  "pozn": "sidlo sa stahuje do Nitry od 1.6.2026",
  "lat": 48.1698902,
  "lon": 17.140156
 },
 {
  "kraj": "BA",
  "kat": "Vyvaren / catering kuchyna",
  "firma": "SHARKAM B&B Catering s.r.o.",
  "ico": "46844341",
  "adresa": "Krokusova 3 (kanc. Technopol, Kutlikova 17)",
  "mesto": "Bratislava-Petrzalka",
  "okres": "Bratislava V",
  "velkost": "3,4 mil EUR; jedalen 850 ludi/den",
  "tel": "+421 915 763 073",
  "email": "bankovich@sharkam.eu",
  "web": "sharkam.eu",
  "zona": "Z3",
  "pozn": "jedalen Technopol + protokolarny catering",
  "lat": 48.1352541,
  "lon": 17.1152978
 },
 {
  "kraj": "BA",
  "kat": "Vyvaren / catering kuchyna",
  "firma": "RC Slovakia s.r.o. (SKIES Catering)",
  "ico": "35870362",
  "adresa": "Vajnorska 100/B",
  "mesto": "Bratislava-Nove Mesto",
  "okres": "Bratislava III",
  "velkost": "1,2 mil EUR; ISO/IFS/BRC",
  "tel": "+421 911 713 000",
  "email": "javorkova@rcslovakia.sk",
  "web": "rcslovakia.sk",
  "zona": "Z2",
  "pozn": "eventy, kongresy",
  "lat": 48.1698902,
  "lon": 17.140156
 },
 {
  "kraj": "BA",
  "kat": "Vyvaren / catering kuchyna",
  "firma": "Timeout Catering s.r.o.",
  "ico": "55083561",
  "adresa": "Polna 4",
  "mesto": "Senec",
  "okres": "Senec",
  "velkost": "event do 1000 ludi",
  "tel": "+421 918 227 782",
  "email": "info@timeoutcatering.sk",
  "web": "timeoutcatering.sk",
  "zona": "Z8",
  "pozn": "pokryva BA + Senec + Pezinok",
  "lat": 48.2086452,
  "lon": 17.4018888
 },
 {
  "kraj": "BA",
  "kat": "Vyvaren / catering kuchyna",
  "firma": "PINO group s.r.o.",
  "ico": "44013141",
  "adresa": "Kadnarova 99",
  "mesto": "Bratislava-Raca",
  "okres": "Bratislava III",
  "velkost": "skolske + firemne jedalne",
  "tel": "+421 904 884 427",
  "email": "objednavky@pinostravovanie.sk",
  "web": "pinostravovanie.sk",
  "zona": "Z2",
  "pozn": "17+ rokov",
  "lat": 48.2053369,
  "lon": 17.1465294
 },
 {
  "kraj": "BA",
  "kat": "Vyvaren / catering kuchyna",
  "firma": "Oldeji (J. Cerna Szalay, zivnost)",
  "ico": "32212721",
  "adresa": "Rusovska cesta 3903/50",
  "mesto": "Bratislava-Petrzalka",
  "okres": "Bratislava V",
  "velkost": "vlastna kuchyna od 1994, 10-19 zam",
  "tel": "0904 630 487",
  "email": "info@oldeji.sk",
  "web": "oldeji.sk",
  "zona": "Z3",
  "pozn": "rozvoz v termonadobach + prevadzka jedalni",
  "lat": 48.1235338,
  "lon": 17.1089883
 },
 {
  "kraj": "BA",
  "kat": "Vyvaren / catering kuchyna",
  "firma": "ALFA FOOD vzs s.r.o.",
  "ico": "55167071",
  "adresa": "Zilinska 7028/1",
  "mesto": "Bratislava-Stare Mesto",
  "okres": "Bratislava I",
  "velkost": "0,62 mil EUR (2024), 25-49 zam",
  "tel": "+421 903 995 595",
  "email": "info@alfafood.sk",
  "web": "alfafood.sk",
  "zona": "Z1",
  "pozn": "zavodne stravovanie",
  "lat": 48.1545738,
  "lon": 17.1112842
 },
 {
  "kraj": "BA",
  "kat": "Vyvaren / catering kuchyna",
  "firma": "ProZeta s.r.o. (Happy Day Catering)",
  "ico": "36739499",
  "adresa": "Padlych hrdinov 24",
  "mesto": "Bratislava-Podunajske Biskupice",
  "okres": "Bratislava II",
  "velkost": "svadby, eventy, firmy",
  "tel": "0948 080 180",
  "email": "info@happy-day.sk",
  "web": "happydaycatering.sk",
  "zona": "Z5",
  "pozn": "16+ rokov",
  "lat": 48.1237261,
  "lon": 17.2123351
 },
 {
  "kraj": "BA",
  "kat": "Vyvaren / catering kuchyna",
  "firma": "TOVAR a SLUZBY s.r.o. (Jedlo Bratislava)",
  "ico": "51725053",
  "adresa": "Popovova 8 (kuchyna Dr. V. Clementisa 5)",
  "mesto": "Bratislava-Ruzinov",
  "okres": "Bratislava II",
  "velkost": "rozvoz obedov",
  "tel": "0905 600 000",
  "email": "",
  "web": "jedlobratislava.sk",
  "zona": "Z2",
  "pozn": "rozvoz po celej BA vratane noci",
  "lat": 48.1608571,
  "lon": 17.1477295
 },
 {
  "kraj": "BA",
  "kat": "Vyvaren / catering kuchyna",
  "firma": "OXA Delivery Service s.r.o.",
  "ico": "50293231",
  "adresa": "Stredna 1",
  "mesto": "Bratislava-Ruzinov",
  "okres": "Bratislava II",
  "velkost": "0,6 mil EUR (2024), 5-9 zam",
  "tel": "",
  "email": "",
  "web": "",
  "zona": "Z2",
  "pozn": "catering pre materske skoly; kontakt cez ORSR",
  "lat": 48.1763819,
  "lon": 17.1703672
 },
 {
  "kraj": "BA",
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Eat & Meet - Mlynska dolina (UK)",
  "ico": "",
  "adresa": "Stare Grunty, blok AD-U, Mlynska dolina",
  "mesto": "Bratislava-Karlova Ves",
  "okres": "Bratislava IV",
  "velkost": "450 miest, 4000+ jedal/den (areal Mlyny az 6000)",
  "tel": "",
  "email": "",
  "web": "eatandmeet.sk",
  "zona": "Z4",
  "pozn": "univerzitna; vlastna prevadzka UK",
  "lat": 48.1641859,
  "lon": 17.0678683
 },
 {
  "kraj": "BA",
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Venza - Mlyny UK",
  "ico": "",
  "adresa": "Mlynska dolina",
  "mesto": "Bratislava-Karlova Ves",
  "okres": "Bratislava IV",
  "velkost": "sucast arealu Mlyny (6000/den)",
  "tel": "",
  "email": "",
  "web": "mlyny.uniba.sk",
  "zona": "Z4",
  "pozn": "univerzitna jedalen",
  "lat": 48.1548435,
  "lon": 17.06991
 },
 {
  "kraj": "BA",
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Jedalen EUBA - Dolnozemska (City Gastro)",
  "ico": "",
  "adresa": "Dolnozemska cesta 1",
  "mesto": "Bratislava-Petrzalka",
  "okres": "Bratislava V",
  "velkost": "500 miest / 1500 pri recepcii",
  "tel": "+421 948 929 323",
  "email": "sekretariat@citygastro.sk",
  "web": "citygastro.sk",
  "zona": "Z3",
  "pozn": "prevadzkuje City Gastro",
  "lat": 48.1275493,
  "lon": 17.1323468
 },
 {
  "kraj": "BA",
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Jedalen Mlada garda (STU)",
  "ico": "",
  "adresa": "Racianska 103",
  "mesto": "Bratislava-Nove Mesto",
  "okres": "Bratislava III",
  "velkost": "136 miest + siet 5-7 jedalni STU",
  "tel": "+421 918 600 162",
  "email": "",
  "web": "stuba.sk",
  "zona": "Z2",
  "pozn": "UZ SDaJ STU",
  "lat": 48.177312,
  "lon": 17.1261017
 },
 {
  "kraj": "BA",
  "kat": "Tackaren / zavodna jedalen",
  "firma": "UNB - Nemocnica Ruzinov",
  "ico": "",
  "adresa": "Ruzinovska 6",
  "mesto": "Bratislava-Ruzinov",
  "okres": "Bratislava II",
  "velkost": ">100k hospitalizacii/rok",
  "tel": "02 48234111",
  "email": "",
  "web": "unb.sk",
  "zona": "Z2",
  "pozn": "vlastna OLVaS; vstup cez verejne obstaravanie",
  "lat": 48.1552301,
  "lon": 17.1519477
 },
 {
  "kraj": "BA",
  "kat": "Tackaren / zavodna jedalen",
  "firma": "UNB - Nem. ak. L. Derera (Kramare)",
  "ico": "",
  "adresa": "Limbova 5",
  "mesto": "Bratislava-Nove Mesto",
  "okres": "Bratislava III",
  "velkost": "velka nemocnica",
  "tel": "",
  "email": "",
  "web": "unb.sk",
  "zona": "Z2",
  "pozn": "vlastna kuchyna, tacovy system",
  "lat": 48.1662606,
  "lon": 17.0863257
 },
 {
  "kraj": "BA",
  "kat": "Tackaren / zavodna jedalen",
  "firma": "UNB - Nem. sv. Cyrila a Metoda (Petrzalka)",
  "ico": "",
  "adresa": "Antolska 11",
  "mesto": "Bratislava-Petrzalka",
  "okres": "Bratislava V",
  "velkost": "velka nemocnica",
  "tel": "",
  "email": "",
  "web": "unb.sk",
  "zona": "Z3",
  "pozn": "vlastna kuchyna",
  "lat": 48.1020874,
  "lon": 17.1183618
 },
 {
  "kraj": "BA",
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Narodny ustav srdc. a cievnych chorob (NUSCH)",
  "ico": "",
  "adresa": "Pod Krasnou horkou 1",
  "mesto": "Bratislava-Kramare",
  "okres": "Bratislava III",
  "velkost": "vlastna kuchyna",
  "tel": "",
  "email": "",
  "web": "nusch.sk",
  "zona": "Z2",
  "pozn": "",
  "lat": 48.1696588,
  "lon": 17.0869479
 },
 {
  "kraj": "BA",
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Narodny onkologicky ustav (NOU)",
  "ico": "",
  "adresa": "Klenova 1",
  "mesto": "Bratislava-Kramare",
  "okres": "Bratislava III",
  "velkost": "vlastna kuchyna, ~200+ lozok",
  "tel": "",
  "email": "",
  "web": "nou.sk",
  "zona": "Z2",
  "pozn": "",
  "lat": 48.1718244,
  "lon": 17.0894784
 },
 {
  "kraj": "BA",
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Nemocnica sv. Michala",
  "ico": "",
  "adresa": "Satinskeho I. 1",
  "mesto": "Bratislava-Stare Mesto",
  "okres": "Bratislava I",
  "velkost": "vlastna OLVaS",
  "tel": "",
  "email": "",
  "web": "nsmas.sk",
  "zona": "Z1",
  "pozn": "vojensko-policajna univ. nemocnica",
  "lat": 48.1452492,
  "lon": 17.1175227
 },
 {
  "kraj": "BA",
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Volkswagen Slovakia - zavodna jedalen",
  "ico": "",
  "adresa": "Jana Jonasa 1",
  "mesto": "Bratislava-Devinska Nova Ves",
  "okres": "Bratislava IV",
  "velkost": "NAJVACSI CIEL: ~11-13 tis. zamestnancov",
  "tel": "",
  "email": "facility/HR",
  "web": "volkswagen.sk",
  "zona": "Z4",
  "pozn": "operator stravovania NEOVERENY - priamy dopyt",
  "lat": 48.2350546,
  "lon": 16.9817538
 },
 {
  "kraj": "BA",
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Slovnaft - zavodna jedalen",
  "ico": "",
  "adresa": "Vlcie hrdlo 1",
  "mesto": "Bratislava-Ruzinov",
  "okres": "Bratislava II",
  "velkost": "velky priemyselny zavod",
  "tel": "",
  "email": "facility",
  "web": "slovnaft.sk",
  "zona": "Z5",
  "pozn": "operator neovereny",
  "lat": 48.1282386,
  "lon": 17.176661
 },
 {
  "kraj": "BA",
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Mondelez SR Production - kantina",
  "ico": "",
  "adresa": "Racianska 44",
  "mesto": "Bratislava-Raca",
  "okres": "Bratislava III",
  "velkost": "~400 zamestnancov",
  "tel": "",
  "email": "",
  "web": "",
  "zona": "Z2",
  "pozn": "cokoladovna",
  "lat": 48.1932309,
  "lon": 17.1416428
 },
 {
  "kraj": "BA",
  "kat": "Tackaren / zavodna jedalen",
  "firma": "La Cantina - Tatracentrum (Bencik)",
  "ico": "",
  "adresa": "Hodzovo nam. 3",
  "mesto": "Bratislava-Stare Mesto",
  "okres": "Bratislava I",
  "velkost": "BC kantina",
  "tel": "",
  "email": "",
  "web": "bencikculinary.sk",
  "zona": "Z1",
  "pozn": "siet kantin v BC (Central, Apollo, Petrzalka)",
  "lat": 48.1484131,
  "lon": 17.1087896
 },
 {
  "kraj": "BA",
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Food Season - Westend Square",
  "ico": "",
  "adresa": "Dubravska cesta 2",
  "mesto": "Bratislava-Karlova Ves",
  "okres": "Bratislava IV",
  "velkost": "firemna kantina",
  "tel": "",
  "email": "",
  "web": "foodseason.sk",
  "zona": "Z4",
  "pozn": "bio suroviny, sous-vide",
  "lat": 48.1686969,
  "lon": 17.0753887
 },
 {
  "kraj": "BA",
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Canteen Priatelia - Westend Tower",
  "ico": "",
  "adresa": "Dubravska cesta 2",
  "mesto": "Bratislava-Karlova Ves",
  "okres": "Bratislava IV",
  "velkost": "firemna kantina",
  "tel": "",
  "email": "",
  "web": "",
  "zona": "Z4",
  "pozn": "",
  "lat": 48.1686969,
  "lon": 17.0753887
 },
 {
  "kraj": "BA",
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Fajne Jedlo - Tower 115",
  "ico": "",
  "adresa": "Pribinova 25",
  "mesto": "Bratislava-Stare Mesto",
  "okres": "Bratislava I",
  "velkost": "samoobsluzna kantina",
  "tel": "",
  "email": "",
  "web": "",
  "zona": "Z1",
  "pozn": "zona Eurovea/Twin City",
  "lat": 48.1411404,
  "lon": 17.1273381
 },
 {
  "kraj": "BA",
  "kat": "Velka restauracia / banketova sala",
  "firma": "Zylinder Cafe & Restaurant",
  "ico": "",
  "adresa": "Hviezdoslavovo nam. 19",
  "mesto": "Bratislava-Stare Mesto",
  "okres": "Bratislava I",
  "velkost": "80 sed / 120 raut + terasa 50",
  "tel": "+421 903 123 134",
  "email": "rezervacie@zylinder.sk",
  "web": "zylinder.sk",
  "zona": "Z1",
  "pozn": "",
  "lat": 48.1419314,
  "lon": 17.1077327
 },
 {
  "kraj": "BA",
  "kat": "Velka restauracia / banketova sala",
  "firma": "Restauracia Matysak (Vinny hotel)",
  "ico": "",
  "adresa": "Holubyho 85",
  "mesto": "Pezinok",
  "okres": "Pezinok",
  "velkost": "130 + terasa 30, banketove priestory",
  "tel": "0907 701 070",
  "email": "restauracia@vinomatysak.sk",
  "web": "restauraciamatysak.sk",
  "zona": "Z7",
  "pozn": "svadby",
  "lat": 48.2883571,
  "lon": 17.2666299
 },
 {
  "kraj": "BA",
  "kat": "Velka restauracia / banketova sala",
  "firma": "Bratislavsky mestiansky pivovar - Drevena",
  "ico": "",
  "adresa": "Drevena 8",
  "mesto": "Bratislava-Stare Mesto",
  "okres": "Bratislava I",
  "velkost": "~180 + terasa 25, salonik 35",
  "tel": "",
  "email": "info@mestianskypivovar.sk",
  "web": "mestianskypivovar.sk",
  "zona": "Z1",
  "pozn": "",
  "lat": 48.1469194,
  "lon": 17.1081791
 },
 {
  "kraj": "BA",
  "kat": "Velka restauracia / banketova sala",
  "firma": "Event Hall Malacky",
  "ico": "",
  "adresa": "Malacky",
  "mesto": "Malacky",
  "okres": "Malacky",
  "velkost": "svadobna sala do 250, vlastna kuchyna",
  "tel": "",
  "email": "",
  "web": "eventhall.sk",
  "zona": "Z6",
  "pozn": "kontakt cez web",
  "lat": 48.4325413,
  "lon": 17.0230915
 },
 {
  "kraj": "BA",
  "kat": "Velka restauracia / banketova sala",
  "firma": "Bratislavsky mestiansky pivovar - Dunajska",
  "ico": "",
  "adresa": "Dunajska 21",
  "mesto": "Bratislava-Stare Mesto",
  "okres": "Bratislava I",
  "velkost": "~280 + terasa 300, salonik 60",
  "tel": "0948 710 888",
  "email": "dunajska@mestianskypivovar.sk",
  "web": "mestianskypivovar.sk",
  "zona": "Z1",
  "pozn": "",
  "lat": 48.1459308,
  "lon": 17.1176901
 },
 {
  "kraj": "BA",
  "kat": "Velka restauracia / banketova sala",
  "firma": "ELESKO Wine Park (Restaurant & Wine bar)",
  "ico": "",
  "adresa": "Partizanska 2275",
  "mesto": "Modra",
  "okres": "Pezinok",
  "velkost": "Zoya Museum 200-400, restauracia 80",
  "tel": "+421 905 704 873",
  "email": "",
  "web": "elesko.sk",
  "zona": "Z7",
  "pozn": "event manager Peter Toth",
  "lat": 48.3541412,
  "lon": 17.3219993
 },
 {
  "kraj": "BA",
  "kat": "Velka restauracia / banketova sala",
  "firma": "Slovak Pub",
  "ico": "",
  "adresa": "Obchodna 62",
  "mesto": "Bratislava-Stare Mesto",
  "okres": "Bratislava I",
  "velkost": "~500 miest (11 miestnosti)",
  "tel": "+421 917 629 221",
  "email": "slovakpub@slovakpub.sk",
  "web": "slovakpub.sk",
  "zona": "Z1",
  "pozn": "",
  "lat": 48.1483346,
  "lon": 17.1124098
 },
 {
  "kraj": "BA",
  "kat": "Velka restauracia / banketova sala",
  "firma": "NH Bratislava Gate One",
  "ico": "",
  "adresa": "Ambrusova 7",
  "mesto": "Bratislava-Ruzinov",
  "okres": "Bratislava II",
  "velkost": "najvacsia sala do 600, 8-10 sal",
  "tel": "",
  "email": "nhgateone@nh-hotels.com",
  "web": "nh-hotels.com",
  "zona": "Z2",
  "pozn": "",
  "lat": 48.1662442,
  "lon": 17.1774457
 },
 {
  "kraj": "BA",
  "kat": "Velka restauracia / banketova sala",
  "firma": "Holiday Inn Bratislava",
  "ico": "",
  "adresa": "Bajkalska 25/A",
  "mesto": "Bratislava-Ruzinov",
  "okres": "Bratislava II",
  "velkost": "6 sal, do 600 hosti",
  "tel": "",
  "email": "",
  "web": "ihg.com",
  "zona": "Z2",
  "pozn": "event kontakt cez IHG",
  "lat": 48.1530346,
  "lon": 17.1488827
 },
 {
  "kraj": "BA",
  "kat": "Velka restauracia / banketova sala",
  "firma": "Dunajsky pivovar (lod/botel)",
  "ico": "",
  "adresa": "Tyrsovo nabrezie",
  "mesto": "Bratislava-Petrzalka",
  "okres": "Bratislava V",
  "velkost": "~600 (terasa 250, salonik 50)",
  "tel": "+421 948 418 934",
  "email": "dunajskypivovar@dunajskypivovar.sk",
  "web": "dunajskypivovar.sk",
  "zona": "Z3",
  "pozn": "",
  "lat": 48.1363762,
  "lon": 17.1132834
 },
 {
  "kraj": "BA",
  "kat": "Velka restauracia / banketova sala",
  "firma": "Hotel Saffron",
  "ico": "",
  "adresa": "Radlinskeho 27",
  "mesto": "Bratislava-Stare Mesto",
  "okres": "Bratislava I",
  "velkost": "6 sal, 1500 m2, do 900 osob",
  "tel": "+421 948 660 459",
  "email": "marketing@hotelsaffron.sk",
  "web": "hotelsaffron.sk",
  "zona": "Z1",
  "pozn": "",
  "lat": 48.1523448,
  "lon": 17.117072
 },
 {
  "kraj": "BA",
  "kat": "Velka restauracia / banketova sala",
  "firma": "Radisson Blu Carlton",
  "ico": "",
  "adresa": "Hviezdoslavovo nam. 3",
  "mesto": "Bratislava-Stare Mesto",
  "okres": "Bratislava I",
  "velkost": "do 1000 hosti",
  "tel": "+421 2 5939 0000",
  "email": "reservation.bratislava@radissonblu.com",
  "web": "radissonhotels.com",
  "zona": "Z1",
  "pozn": "",
  "lat": 48.1412124,
  "lon": 17.1085808
 },
 {
  "kraj": "BA",
  "kat": "Velka restauracia / banketova sala",
  "firma": "Hotel Senec (Lake & Aqua Resort)",
  "ico": "",
  "adresa": "Slnecne jazera-Sever",
  "mesto": "Senec",
  "okres": "Senec",
  "velkost": "kongres do 1000 (svadby do ~300)",
  "tel": "+421 904 543 513",
  "email": "kakasova@hotelsenec.sk",
  "web": "hotelsenec.sk",
  "zona": "Z8",
  "pozn": "event Stela Kakasova",
  "lat": 48.2215028,
  "lon": 17.4005824
 },
 {
  "kraj": "BA",
  "kat": "Velka restauracia / banketova sala",
  "firma": "Sheraton Bratislava",
  "ico": "",
  "adresa": "Pribinova 12",
  "mesto": "Bratislava-Stare Mesto",
  "okres": "Bratislava I",
  "velkost": "ballroom do 400, standing do 1500",
  "tel": "",
  "email": "",
  "web": "marriott.com",
  "zona": "Z1",
  "pozn": "Eurovea; event cez Marriott MICE",
  "lat": 48.1403976,
  "lon": 17.1223178
 },
 {
  "kraj": "BA",
  "kat": "Velka restauracia / banketova sala",
  "firma": "Park Inn by Radisson Danube",
  "ico": "",
  "adresa": "Rybne nam. 1",
  "mesto": "Bratislava-Stare Mesto",
  "okres": "Bratislava I",
  "velkost": "event 471 m2, do 400 delegatov",
  "tel": "",
  "email": "",
  "web": "radissonhotels.com",
  "zona": "Z1",
  "pozn": "",
  "lat": 48.1404872,
  "lon": 17.1050761
 },
 {
  "kraj": "BA",
  "kat": "Velka restauracia / banketova sala",
  "firma": "Falkensteiner Hotel Bratislava",
  "ico": "",
  "adresa": "Pilarikova 5",
  "mesto": "Bratislava-Stare Mesto",
  "okres": "Bratislava I",
  "velkost": "sala 173 m2, recepcia do 300",
  "tel": "+421 2 5923 6100",
  "email": "",
  "web": "falkensteiner.com",
  "zona": "Z1",
  "pozn": "",
  "lat": 48.1460616,
  "lon": 17.1034683
 },
 {
  "kraj": "BA",
  "kat": "Velka restauracia / banketova sala",
  "firma": "Grand Hotel River Park (Luxury Collection)",
  "ico": "",
  "adresa": "Dvorakovo nabrezie 6",
  "mesto": "Bratislava-Stare Mesto",
  "okres": "Bratislava I",
  "velkost": "banketove saly",
  "tel": "",
  "email": "",
  "web": "grandriverpark.sk",
  "zona": "Z1",
  "pozn": "event cez Marriott",
  "lat": 48.1414165,
  "lon": 17.0903098
 },
 {
  "kraj": "BA",
  "kat": "Velka restauracia / banketova sala",
  "firma": "Koliba Senec",
  "ico": "",
  "adresa": "Slnecne jazera-Sever",
  "mesto": "Senec",
  "okres": "Senec",
  "velkost": "svadby/oslavy/firemne, bazen, ubytovanie",
  "tel": "+421 908 602 020",
  "email": "",
  "web": "kolibasenec.sk",
  "zona": "Z8",
  "pozn": "",
  "lat": 48.2215028,
  "lon": 17.4005824
 },
 {
  "kraj": "BA",
  "kat": "Velka restauracia / banketova sala",
  "firma": "Stara trznica",
  "ico": "",
  "adresa": "Namestie SNP 25",
  "mesto": "Bratislava-Stare Mesto",
  "okres": "Bratislava I",
  "velkost": "multifunkcna hala, velke eventy",
  "tel": "+421 948 420 999",
  "email": "trznica@staratrznica.sk",
  "web": "staratrznica.sk",
  "zona": "Z1",
  "pozn": "catering externy",
  "lat": 48.1448115,
  "lon": 17.1112785
 },
 {
  "kraj": "BA",
  "kat": "Velka restauracia / banketova sala",
  "firma": "Restauracia Zeleny dvor",
  "ico": "",
  "adresa": "M. R. Stefanika 110",
  "mesto": "Malacky",
  "okres": "Malacky",
  "velkost": "svadby/oslavy/firemne",
  "tel": "+421 917 977 311",
  "email": "",
  "web": "zelenydvormalacky.sk",
  "zona": "Z6",
  "pozn": "",
  "lat": 48.425248,
  "lon": 17.0201504
 },
 {
  "kraj": "BA",
  "kat": "Velka restauracia / banketova sala",
  "firma": "Penzion Palenica",
  "ico": "",
  "adresa": "Bernolakovo",
  "mesto": "Bernolakovo",
  "okres": "Senec",
  "velkost": "terasova miestnost ~100, restauracia 60",
  "tel": "",
  "email": "",
  "web": "penzionpalenica.eu",
  "zona": "Z8",
  "pozn": "",
  "lat": 48.1989817,
  "lon": 17.3000328
 },
 {
  "kraj": "BA",
  "kat": "Velka restauracia / banketova sala",
  "firma": "RIVERBANK Restaurant",
  "ico": "",
  "adresa": "Dvorakovo nabrezie 6",
  "mesto": "Bratislava-Stare Mesto",
  "okres": "Bratislava I",
  "velkost": "fine-dining pri Dunaji",
  "tel": "+421 910 872 168",
  "email": "",
  "web": "riverbank.sk",
  "zona": "Z1",
  "pozn": "pri Grand Hotel River Park",
  "lat": 48.1414165,
  "lon": 17.0903098
 },
 {
  "kraj": "BA",
  "kat": "Velka restauracia / banketova sala",
  "firma": "Hotel Nostalgia",
  "ico": "",
  "adresa": "Senec",
  "mesto": "Senec",
  "okres": "Senec",
  "velkost": "sala do ~120 s parketom",
  "tel": "",
  "email": "",
  "web": "hotelnostalgia.sk",
  "zona": "Z8",
  "pozn": "svadby/oslavy",
  "lat": 48.2199473,
  "lon": 17.3969901
 },
 {
  "kraj": "BA",
  "kat": "Restauracna siet (3+ prevadzok)",
  "firma": "KRUH remeselna pekaren (Kruh remeselna vyroba s.r.o.)",
  "ico": "47762799",
  "adresa": "Kutuzovova 11 (sidlo)",
  "mesto": "Bratislava-Nove Mesto",
  "okres": "Bratislava III",
  "velkost": "3 prevadzky",
  "tel": "+421 915 512 230",
  "email": "ahoj@kruhpekaren.sk",
  "web": "kruhpekaren.sk",
  "zona": "Z2",
  "pozn": "3 prevadzky (siet remeselnych pekarni)",
  "lat": 48.1647644,
  "lon": 17.1307846
 },
 {
  "kraj": "BA",
  "kat": "Restauracna siet (3+ prevadzok)",
  "firma": "Triple Five Coffee",
  "ico": "47117311",
  "adresa": "Jozefska 2A",
  "mesto": "Bratislava-Stare Mesto",
  "okres": "Bratislava I",
  "velkost": "3 prevadzky",
  "tel": "0940 629 026",
  "email": "",
  "web": "triplefivecoffee.com",
  "zona": "Z1",
  "pozn": "3 prevadzky",
  "lat": 48.1509638,
  "lon": 17.1096081
 },
 {
  "kraj": "BA",
  "kat": "Restauracna siet (3+ prevadzok)",
  "firma": "Fresh Garden Salads (FRESH GARDEN s.r.o.)",
  "ico": "45522464",
  "adresa": "Plynarenska 2/A",
  "mesto": "Bratislava-Ruzinov",
  "okres": "Bratislava II",
  "velkost": "3 prevadzky",
  "tel": "+421 902 311 331",
  "email": "info@freshgarden.sk",
  "web": "freshgarden.sk",
  "zona": "Z2",
  "pozn": "3 prevadzky",
  "lat": 48.1462765,
  "lon": 17.1419155
 },
 {
  "kraj": "BA",
  "kat": "Restauracna siet (3+ prevadzok)",
  "firma": "Pulitzer family (RIVAS s.r.o.)",
  "ico": "35946008",
  "adresa": "Drobneho 21 (sidlo)",
  "mesto": "Bratislava-Dubravka",
  "okres": "Bratislava IV",
  "velkost": "3 restauracie fine-dining",
  "tel": "",
  "email": "",
  "web": "",
  "zona": "Z4",
  "pozn": "Stefanka, Pulitzer, U zlateho jelena",
  "lat": 48.1914663,
  "lon": 17.0408338
 },
 {
  "kraj": "BA",
  "kat": "Restauracna siet (3+ prevadzok)",
  "firma": "Domino's Pizza (APIM Gastro s.r.o.)",
  "ico": "50616951",
  "adresa": "Sartorisova 11 (sidlo)",
  "mesto": "Bratislava-Ruzinov",
  "okres": "Bratislava II",
  "velkost": "4 prevadzky",
  "tel": "",
  "email": "",
  "web": "dominospizza.sk",
  "zona": "Z2",
  "pozn": "4 prevadzky",
  "lat": 48.1568421,
  "lon": 17.1419539
 },
 {
  "kraj": "BA",
  "kat": "Restauracna siet (3+ prevadzok)",
  "firma": "EDO-KIN GROUP s.r.o.",
  "ico": "46988882",
  "adresa": "Raztocna 25 (sidlo)",
  "mesto": "Bratislava-Vrakuna",
  "okres": "Bratislava II",
  "velkost": "4 prevadzky, trzby 2,84 mil EUR (2024)",
  "tel": "",
  "email": "",
  "web": "",
  "zona": "Z5",
  "pozn": "4 prevadzky",
  "lat": 48.1491794,
  "lon": 17.2137098
 },
 {
  "kraj": "BA",
  "kat": "Restauracna siet (3+ prevadzok)",
  "firma": "Coffeeshop Company CEE s.r.o.",
  "ico": "35689498",
  "adresa": "Janoskova 4 (sidlo)",
  "mesto": "Bratislava-Nove Mesto",
  "okres": "Bratislava III",
  "velkost": "5-6 kaviarni",
  "tel": "",
  "email": "",
  "web": "coffeeshopcompany.com",
  "zona": "Z2",
  "pozn": "5-6 kaviarni",
  "lat": 48.1754477,
  "lon": 17.132832
 },
 {
  "kraj": "BA",
  "kat": "Restauracna siet (3+ prevadzok)",
  "firma": "Regal Burger s.r.o.",
  "ico": "47581930",
  "adresa": "sidlo Drahovce (prevadzky v BA)",
  "mesto": "Bratislava",
  "okres": "Bratislava I",
  "velkost": "5-6 prevadzok",
  "tel": "",
  "email": "info@regalburger.com",
  "web": "regalburger.eu",
  "zona": "Z2",
  "pozn": "5-6 prevadzok v BA; sidlo Drahovce (mimo BA kraja)",
  "lat": 48.1516988,
  "lon": 17.1093063
 },
 {
  "kraj": "BA",
  "kat": "Restauracna siet (3+ prevadzok)",
  "firma": "Bevanda",
  "ico": "doplnit",
  "adresa": "Kubacova 23",
  "mesto": "Bratislava-Raca",
  "okres": "Bratislava III",
  "velkost": "6 restauracii",
  "tel": "+421 905 551 705",
  "email": "bevanda@bevanda.sk",
  "web": "bevanda.sk",
  "zona": "Z2",
  "pozn": "6 restauracii",
  "lat": 48.2117407,
  "lon": 17.153861
 },
 {
  "kraj": "BA",
  "kat": "Restauracna siet (3+ prevadzok)",
  "firma": "Mondieu (MONDIEU BRATISLAVA s.r.o.)",
  "ico": "47114533",
  "adresa": "Mileticova 1 (sidlo)",
  "mesto": "Bratislava-Ruzinov",
  "okres": "Bratislava II",
  "velkost": "7 kaviarni",
  "tel": "",
  "email": "info@mondieu.sk",
  "web": "mondieu.sk",
  "zona": "Z2",
  "pozn": "7 kaviarni",
  "lat": 48.1577489,
  "lon": 17.1310655
 },
 {
  "kraj": "BA",
  "kat": "Restauracna siet (3+ prevadzok)",
  "firma": "Veg Life s.r.o.",
  "ico": "46880526",
  "adresa": "Dubravska cesta 14 (sidlo)",
  "mesto": "Bratislava-Karlova Ves",
  "okres": "Bratislava IV",
  "velkost": "8 bistro prevadzok",
  "tel": "0905 295 165",
  "email": "info@veglife.sk",
  "web": "veglife.sk",
  "zona": "Z4",
  "pozn": "cisty 1 kontakt - dobry B2B lead",
  "lat": 48.1710686,
  "lon": 17.0712854
 },
 {
  "kraj": "BA",
  "kat": "Restauracna siet (3+ prevadzok)",
  "firma": "SPUSTA Kaviaren & Pekaren",
  "ico": "31640826",
  "adresa": "Pifflova 6",
  "mesto": "Bratislava-Petrzalka",
  "okres": "Bratislava V",
  "velkost": "17-18 prevadzok (vratane Senec, Pezinok)",
  "tel": "+421 918 689 366",
  "email": "info@spustakaviaren.sk",
  "web": "spustakaviaren.sk",
  "zona": "Z3",
  "pozn": "aj okresy; 2. ICO 35803568",
  "lat": 48.1269838,
  "lon": 17.1081707
 },
 {
  "kraj": "BA",
  "kat": "Restauracna siet (3+ prevadzok)",
  "firma": "AmRest Coffee SK s.r.o. (Starbucks)",
  "ico": "50088971",
  "adresa": "Pajstunska 3 (sidlo)",
  "mesto": "Bratislava-Petrzalka",
  "okres": "Bratislava V",
  "velkost": "Starbucks 6-7 + KFC/BK/PizzaHut",
  "tel": "",
  "email": "",
  "web": "starbucksslovakia.sk",
  "zona": "Z3",
  "pozn": "skupina AmRest, viac brandov",
  "lat": 48.1111834,
  "lon": 17.1029997
 },
 {
  "kraj": "BA",
  "kat": "Restauracna siet (3+ prevadzok)",
  "firma": "Queensway Restaurants Slovakia s.r.o. (KFC + Pizza Hut)",
  "ico": "35852143",
  "adresa": "Pribinova 4, Eurovea Central 1",
  "mesto": "Bratislava-Stare Mesto",
  "okres": "Bratislava I",
  "velkost": "~20,5 mil EUR; KFC 7 + Pizza Hut 3",
  "tel": "",
  "email": "",
  "web": "kfcslovakia.sk",
  "zona": "Z1",
  "pozn": "over aktualnu entitu (AmRest)",
  "lat": 48.1534392,
  "lon": 17.1151016
 },
 {
  "kraj": "BA",
  "kat": "Restauracna siet (3+ prevadzok)",
  "firma": "McDonald's Slovakia spol. s r.o.",
  "ico": "31392229",
  "adresa": "Einsteinova 33",
  "mesto": "Bratislava-Petrzalka",
  "okres": "Bratislava V",
  "velkost": "52,45 mil EUR (2024); ~18 prevadzok v kraji",
  "tel": "",
  "email": "",
  "web": "mcdonalds.sk",
  "zona": "Z3",
  "pozn": "NAJVACSI retazec; +Pezinok",
  "lat": 48.13244,
  "lon": 17.10755
 },
 {
  "kraj": "TT",
  "kat": "Catering dodavatel",
  "firma": "Frape catering s.r.o.",
  "ico": "44178450",
  "adresa": "Hudobna 7",
  "mesto": "Trnava",
  "okres": "Trnava",
  "velkost": "trzby 3,6 mil EUR (2025), 10-19 zam",
  "tel": "033/293 33 22",
  "email": "mail@frape-catering.sk",
  "web": "frape-catering.sk",
  "zona": "T1",
  "pozn": "SILNY CIEL; komplexny catering + rozvoz; dodava pre soc. zariadenia TTSK; sidlo Hudobna 9715/7, prevadzka Pekarska 40A, office Jana Holleho 5; konatel D. Schmidt 0903 246 244",
  "lat": 48.3678367,
  "lon": 17.5567561
 },
 {
  "kraj": "TT",
  "kat": "Catering dodavatel",
  "firma": "Catering Majernik s.r.o.",
  "ico": "50803549",
  "adresa": "Slnecna 6",
  "mesto": "Vrbove",
  "okres": "Piestany",
  "velkost": "trzby 2-3 mil EUR (2025), 20-24 zam",
  "tel": "",
  "email": "",
  "web": "",
  "zona": "T3",
  "pozn": "SILNY CIEL; rodinny catering 20+ rokov, zavodne stravovanie Vrbove/Piestany/Trnava",
  "lat": 48.6238782,
  "lon": 17.7167624
 },
 {
  "kraj": "TT",
  "kat": "Catering dodavatel",
  "firma": "La Cantine (cantineparty)",
  "ico": "doplnit ORSR",
  "adresa": "doplnit",
  "mesto": "Trnava",
  "okres": "Trnava",
  "velkost": "catering oblozene/party misy, firemne aj sukromne akcie",
  "tel": "",
  "email": "",
  "web": "cantineparty.sk",
  "zona": "T1",
  "pozn": "cateringova firma Trnava; ICO + adresa doplnit ORSR",
  "lat": 48.374218,
  "lon": 17.5809299
 },
 {
  "kraj": "TT",
  "kat": "Catering dodavatel",
  "firma": "Catering Relax Trnava",
  "ico": "doplnit ORSR",
  "adresa": "Piestanska 3",
  "mesto": "Trnava",
  "okres": "Trnava",
  "velkost": "rozvoz stravy pre firmy, denne menu, catering podujati",
  "tel": "",
  "email": "",
  "web": "",
  "zona": "T1",
  "pozn": "over ci nie je prepojeny s TOP-RELAX brand; ICO doplnit",
  "lat": 48.384791,
  "lon": 17.6005036
 },
 {
  "kraj": "TT",
  "kat": "Catering dodavatel",
  "firma": "SEDA Catering (Katarina Sediva)",
  "ico": "54787572",
  "adresa": "Petrovska 4",
  "mesto": "Skalica",
  "okres": "Skalica",
  "velkost": "SZCO; catering svadby/firemne, okres Skalica + Senica",
  "tel": "",
  "email": "info@sedacatering.sk",
  "web": "sedacatering.sk",
  "zona": "T5",
  "pozn": "mensia kapacita",
  "lat": 48.848089,
  "lon": 17.2390985
 },
 {
  "kraj": "TT",
  "kat": "Catering dodavatel",
  "firma": "LARK - CATERING s.r.o.",
  "ico": "46939342",
  "adresa": "Pod Hajkom 2",
  "mesto": "Skalica",
  "okres": "Skalica",
  "velkost": "pekarska/cukrarska vyroba + catering + teple jedla",
  "tel": "034 664 5164",
  "email": "sikulova@larksro.sk",
  "web": "larkskalica.sk",
  "zona": "T5",
  "pozn": "SILNY CIEL; catering + vlastna vyroba, vyssi objem surovin",
  "lat": 48.8385401,
  "lon": 17.2297234
 },
 {
  "kraj": "TT",
  "kat": "Catering dodavatel",
  "firma": "Kralovsky Catering",
  "ico": "doplnit ORSR",
  "adresa": "doplnit",
  "mesto": "Skalica",
  "okres": "Skalica",
  "velkost": "premium catering svadby/firemne od 15 osob",
  "tel": "0910 646 604",
  "email": "info@kralovskycatering.sk",
  "web": "kralovskycatering.sk",
  "zona": "T5",
  "pozn": "regionalny hrac Skalica + Senica; ICO doplnit",
  "lat": 48.8461007,
  "lon": 17.2287837
 },
 {
  "kraj": "TT",
  "kat": "Catering dodavatel",
  "firma": "Catering 4 Events",
  "ico": "doplnit ORSR",
  "adresa": "doplnit",
  "mesto": "Piestany",
  "okres": "Piestany",
  "velkost": "catering festivaly/plesy/svadby + prenajom stanov",
  "tel": "",
  "email": "",
  "web": "catering4events.sk",
  "zona": "T3",
  "pozn": "eventovy catering, sezonny vyssi objem",
  "lat": 48.5895247,
  "lon": 17.8213848
 },
 {
  "kraj": "TT",
  "kat": "Catering dodavatel",
  "firma": "Catering Piestany",
  "ico": "doplnit ORSR",
  "adresa": "doplnit",
  "mesto": "Piestany",
  "okres": "Piestany",
  "velkost": "sala 280 m2, kapacita 150 osob; catering",
  "tel": "",
  "email": "",
  "web": "cateringpiestany.sk",
  "zona": "T3",
  "pozn": "vlastny party priestor + catering",
  "lat": 48.5895247,
  "lon": 17.8213848
 },
 {
  "kraj": "TT",
  "kat": "Vyvaren / catering kuchyna",
  "firma": "TOP-RELAX s.r.o.",
  "ico": "36836061",
  "adresa": "Rybnikova 16",
  "mesto": "Trnava",
  "okres": "Trnava",
  "velkost": "trzby 10,0 mil EUR (2025), 150-199 zam",
  "tel": "",
  "email": "",
  "web": "top-relax.sk",
  "zona": "T1",
  "pozn": "SILNY CIEL; zavodne stravovanie, vending, dovoz jedal; prevadzkuje jedalen UCM",
  "lat": 48.3826049,
  "lon": 17.5848061
 },
 {
  "kraj": "TT",
  "kat": "Vyvaren / catering kuchyna",
  "firma": "Grand Gastro s.r.o.",
  "ico": "50601237",
  "adresa": "29. augusta 9",
  "mesto": "Galanta",
  "okres": "Galanta",
  "velkost": "trzby 4,41 mil EUR (2024), 50-99 zam",
  "tel": "",
  "email": "",
  "web": "grandgastro.sk",
  "zona": "T7",
  "pozn": "SILNY CIEL; dodavatel zavodneho a skolskeho stravovania, 30+ rokov; pozn. mala strata + nedoplatky 2024",
  "lat": 48.1868596,
  "lon": 17.7223147
 },
 {
  "kraj": "TT",
  "kat": "Vyvaren / catering kuchyna",
  "firma": "Gastro DS s.r.o.",
  "ico": "50808478",
  "adresa": "Alzbetinske namestie 1203",
  "mesto": "Dunajska Streda",
  "okres": "Dunajska Streda",
  "velkost": "trzby 2,28 mil EUR (2025), 50-99 zam",
  "tel": "+421 31 286 50 48",
  "email": "gastrods@dunstreda.sk",
  "web": "gastrods.sk",
  "zona": "T6",
  "pozn": "SILNY CIEL; mestska firma, skolske jedalne vsetkych ZS/MS/gymnazii DS",
  "lat": 47.9962553,
  "lon": 17.6143437
 },
 {
  "kraj": "TT",
  "kat": "Vyvaren / catering kuchyna",
  "firma": "Gastro-Tief s.r.o.",
  "ico": "47345195",
  "adresa": "Tamaskovicova 13",
  "mesto": "Trnava",
  "okres": "Trnava",
  "velkost": "trzby 0,25 mil EUR (2025), 10-19 zam",
  "tel": "0919 300 140",
  "email": "tief@tief.sk",
  "web": "tief.sk",
  "zona": "T1",
  "pozn": "rozvoz hotovych jedal Trnava; mensia kapacita",
  "lat": 48.3672675,
  "lon": 17.5959372
 },
 {
  "kraj": "TT",
  "kat": "Vyvaren / catering kuchyna",
  "firma": "IN-food-catering s.r.o.",
  "ico": "53118839",
  "adresa": "Abraham 452",
  "mesto": "Abraham",
  "okres": "Galanta",
  "velkost": "trzby 0,46 mil EUR (2025), 5-9 zam",
  "tel": "",
  "email": "",
  "web": "",
  "zona": "T7",
  "pozn": "restauracne cinnosti + catering",
  "lat": 48.2479831,
  "lon": 17.6194193
 },
 {
  "kraj": "TT",
  "kat": "Vyvaren / catering kuchyna",
  "firma": "Robert Csoka - RODETT",
  "ico": "doplnit ORSR",
  "adresa": "doplnit",
  "mesto": "Luc na Ostrove",
  "okres": "Dunajska Streda",
  "velkost": "SZCO; vyroba a rozvoz teplych jedal od 1997",
  "tel": "",
  "email": "",
  "web": "rodett.sk",
  "zona": "T6",
  "pozn": "rozvoz DS/Velky Meder/Samorin + catering; ICO SZCO doplnit",
  "lat": 47.9754375,
  "lon": 17.5224297
 },
 {
  "kraj": "TT",
  "kat": "Vyvaren / catering kuchyna",
  "firma": "Grand Gastro Catering s.r.o.",
  "ico": "50770667",
  "adresa": "doplnit",
  "mesto": "Galanta",
  "okres": "Galanta",
  "velkost": "prepojena firma ku Grand Gastro",
  "tel": "",
  "email": "",
  "web": "grandgastro.sk",
  "zona": "T7",
  "pozn": "sesterska firma zavodne stravovanie; trzby/adresa over FinStat",
  "lat": 48.1910498,
  "lon": 17.7270629
 },
 {
  "kraj": "TT",
  "kat": "Tackaren / zavodna jedalen",
  "firma": "PCA Slovakia s.r.o. (Stellantis Trnava)",
  "ico": "36256013",
  "adresa": "Automobilova 1",
  "mesto": "Trnava",
  "okres": "Trnava",
  "velkost": "zavodna jedalen 4000-4999 zam, trzby 2,03 mld EUR (2024)",
  "tel": "",
  "email": "",
  "web": "stellantis-slovakia.sk",
  "zona": "T1",
  "pozn": "SILNY CIEL; najvacsi zamestnavatel okresu (automobilka); operator jedalne neovereny",
  "lat": 48.362353,
  "lon": 17.6192737
 },
 {
  "kraj": "TT",
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Fakultna nemocnica Trnava",
  "ico": "00610381",
  "adresa": "A. Zarnova 11",
  "mesto": "Trnava",
  "okres": "Trnava",
  "velkost": "vlastna kuchyna, 641 luzok, 1000-1999 zam",
  "tel": "033/5938111",
  "email": "fntt@fntt.sk",
  "web": "fntt.sk",
  "zona": "T1",
  "pozn": "SILNY CIEL; nemocnicna kuchyna pacienti + personal; verejny obstaravatel",
  "lat": 48.374218,
  "lon": 17.5809299
 },
 {
  "kraj": "TT",
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Saneca Pharmaceuticals a.s.",
  "ico": "46833323",
  "adresa": "Nitrianska 100",
  "mesto": "Hlohovec",
  "okres": "Hlohovec",
  "velkost": "500-999 zam (~800), trzby 108,8 mil EUR (2025)",
  "tel": "",
  "email": "info@saneca.com",
  "web": "saneca.com",
  "zona": "T2",
  "pozn": "SILNY CIEL; najvacsi zamestnavatel okresu Hlohovec (byv. Slovakofarma/Zentiva areal)",
  "lat": 48.4214265,
  "lon": 17.8147037
 },
 {
  "kraj": "TT",
  "kat": "Tackaren / zavodna jedalen",
  "firma": "ZF SACHS Slovakia a.s.",
  "ico": "doplnit ORSR",
  "adresa": "Strojarenska 2",
  "mesto": "Trnava",
  "okres": "Trnava",
  "velkost": "~3100 zam, zavodna jedalen",
  "tel": "",
  "email": "",
  "web": "zf.com",
  "zona": "T1",
  "pozn": "SILNY CIEL; automotive priem. park Trnava; ICO doplnit ORSR",
  "lat": 48.3567915,
  "lon": 17.5706494
 },
 {
  "kraj": "TT",
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Univerzita sv. Cyrila a Metoda (UCM)",
  "ico": "36078913",
  "adresa": "Namestie J. Herdu 2",
  "mesto": "Trnava",
  "okres": "Trnava",
  "velkost": "studentska jedalen; catering prevadzkuje TOP-RELAX",
  "tel": "033/5565111",
  "email": "",
  "web": "ucm.sk",
  "zona": "T1",
  "pozn": "objednavatel; dodavatela jedla riesi TOP-RELAX",
  "lat": 48.374218,
  "lon": 17.5809299
 },
 {
  "kraj": "TT",
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Trnavska univerzita (TRUNI)",
  "ico": "31825249",
  "adresa": "Hornopotocna 23",
  "mesto": "Trnava",
  "okres": "Trnava",
  "velkost": "studentska jedalen, koncesia na prevadzku",
  "tel": "033/5939111",
  "email": "",
  "web": "truni.sk",
  "zona": "T1",
  "pozn": "stravovanie cez externeho prevadzkovatela; ICO over ORSR",
  "lat": 48.379698,
  "lon": 17.58686
 },
 {
  "kraj": "TT",
  "kat": "Tackaren / zavodna jedalen",
  "firma": "SAMSUNG Electronics Slovakia s.r.o.",
  "ico": "36249564",
  "adresa": "Hviezdoslavova 807",
  "mesto": "Galanta",
  "okres": "Galanta",
  "velkost": "trzby 1,77 mld EUR (2024); velka zavodna jedalen, tisice cez agentury",
  "tel": "031 7882111",
  "email": "sesk@samsung.com",
  "web": "samsung.com/sk",
  "zona": "T7",
  "pozn": "SILNY CIEL; najvacsia fabrika regionu; over operatora jedalne",
  "lat": 48.1860755,
  "lon": 17.7337498
 },
 {
  "kraj": "TT",
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Nemocnica Sv. Lukasa Galanta a.s.",
  "ico": "44452519",
  "adresa": "Hodska 38",
  "mesto": "Galanta",
  "okres": "Galanta",
  "velkost": "447 lozok, ~649 zam",
  "tel": "",
  "email": "",
  "web": "pentahospitals.sk",
  "zona": "T7",
  "pozn": "SILNY CIEL; nemocnicna kuchyna; siet Svet zdravia/Penta",
  "lat": 48.1957203,
  "lon": 17.7213597
 },
 {
  "kraj": "TT",
  "kat": "Tackaren / zavodna jedalen",
  "firma": "NsP Dunajska Streda a.s.",
  "ico": "44455356",
  "adresa": "Velkoblahovska 23",
  "mesto": "Dunajska Streda",
  "okres": "Dunajska Streda",
  "velkost": "~244 lozok; Svet zdravia/Penta",
  "tel": "",
  "email": "",
  "web": "pentahospitals.sk",
  "zona": "T6",
  "pozn": "SILNY CIEL; nemocnicna kuchyna; over interny vs cateringovy model",
  "lat": 48.0009648,
  "lon": 17.6046308
 },
 {
  "kraj": "TT",
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Schaeffler Skalica spol. s r.o.",
  "ico": "30998140",
  "adresa": "Dr. G. Schaefflera 1",
  "mesto": "Skalica",
  "okres": "Skalica",
  "velkost": "trzby 455,1 mil EUR (2024), 3000-3999 zam",
  "tel": "034 696 1111",
  "email": "",
  "web": "schaeffler.sk",
  "zona": "T5",
  "pozn": "SILNY CIEL; fabrika, velka zavodna jedalen, tisice obedov/den (byv. INA Skalica)",
  "lat": 48.8497319,
  "lon": 17.2116194
 },
 {
  "kraj": "TT",
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Fakultna nemocnica AGEL Skalica a.s.",
  "ico": "44444761",
  "adresa": "Koreszkova 7",
  "mesto": "Skalica",
  "okres": "Skalica",
  "velkost": "spadova oblast 120000+; lozkova nemocnica",
  "tel": "034 6212 111",
  "email": "",
  "web": "nemocnicaskalica.agel.sk",
  "zona": "T5",
  "pozn": "SILNY CIEL; nemocnicna prevadzka; skupina AGEL",
  "lat": 48.8440909,
  "lon": 17.2269808
 },
 {
  "kraj": "TT",
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Nemocnica Alexandra Wintera n.o.",
  "ico": "36084221",
  "adresa": "Winterova 66",
  "mesto": "Piestany",
  "okres": "Piestany",
  "velkost": "lozkova nemocnica Piestany, pacienti + personal",
  "tel": "033 7955 111",
  "email": "",
  "web": "nawpiestany.sk",
  "zona": "T3",
  "pozn": "SILNY CIEL; nemocnicna kuchyna, stabilny denny objem",
  "lat": 48.5880562,
  "lon": 17.8381581
 },
 {
  "kraj": "TT",
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Mestska poliklinika Senica a.s.",
  "ico": "36273074",
  "adresa": "Sotinska 1",
  "mesto": "Senica",
  "okres": "Senica",
  "velkost": "poliklinika; ambulantne + lozkove sluzby",
  "tel": "034 698 7111",
  "email": "",
  "web": "poliklinikase.sk",
  "zona": "T4",
  "pozn": "Senica nema lozkovu nemocnicu, spada pod FN AGEL Skalica; stredny objem",
  "lat": 48.6883138,
  "lon": 17.372334
 },
 {
  "kraj": "TT",
  "kat": "Tackaren / zavodna jedalen",
  "firma": "OMS a.s.",
  "ico": "34132333",
  "adresa": "Dojc 419",
  "mesto": "Dojc",
  "okres": "Senica",
  "velkost": "~2,9 mil EUR; historicky ~950 zam, vyrobca svietidiel",
  "tel": "034 694 0411",
  "email": "",
  "web": "oms.eu",
  "zona": "T4",
  "pozn": "vyrobny zavod s jedalnou; firma v restrukturalizacii; over aktualny pocet zam",
  "lat": 48.6771217,
  "lon": 17.254151
 },
 {
  "kraj": "TT",
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Slovenske liecebne kupele Piestany a.s.",
  "ico": "34144790",
  "adresa": "Winterova 29",
  "mesto": "Piestany",
  "okres": "Piestany",
  "velkost": "trzby 51,4 mil EUR; hotely Thermia Palace/Esplanade/Splendid/Grand, tisice stravnikov/den",
  "tel": "033 775 7733",
  "email": "spa@ensanahotels.com",
  "web": "ensanahotels.com/sk",
  "zona": "T3",
  "pozn": "SILNY CIEL; najvacsi prevadzkovatel stravovania v kraji, vlastne kuchyne + liecebna vyziva",
  "lat": 48.5894483,
  "lon": 17.8364459
 },
 {
  "kraj": "TT",
  "kat": "Velka restauracia / banketova sala",
  "firma": "Sladovna SESSLER a.s.",
  "ico": "36253774",
  "adresa": "Pri Kalvarii 17",
  "mesto": "Trnava",
  "okres": "Trnava",
  "velkost": "svadobna sala 120 (200 m2), restauracia + minipivovar + penzion + kongres",
  "tel": "",
  "email": "",
  "web": "sessler.sk",
  "zona": "T1",
  "pozn": "SILNY CIEL; komplex s vlastnou varnou kapacitou, eventovy priestor",
  "lat": 48.3889107,
  "lon": 17.5760428
 },
 {
  "kraj": "TT",
  "kat": "Velka restauracia / banketova sala",
  "firma": "Jaster s.r.o.",
  "ico": "36708364",
  "adresa": "Stara hora 1",
  "mesto": "Hlohovec",
  "okres": "Hlohovec",
  "velkost": "restauracia 230 miest, sala 80-150, 2 vinarne 2x50",
  "tel": "033/7424862",
  "email": "tutura.pavol@gmail.com",
  "web": "jaster-hlohovec.sk",
  "zona": "T2",
  "pozn": "SILNY CIEL; najvacsi banketovy priestor okresu Hlohovec; majitel P. Tutura 0903473379",
  "lat": 48.4497091,
  "lon": 17.8114153
 },
 {
  "kraj": "TT",
  "kat": "Velka restauracia / banketova sala",
  "firma": "Victoria Trnava",
  "ico": "doplnit ORSR",
  "adresa": "doplnit",
  "mesto": "Trnava",
  "okres": "Trnava",
  "velkost": "sala do 75 + terasy 40, eventova restauracia svadby/firmy",
  "tel": "",
  "email": "",
  "web": "victoriatrnava.sk",
  "zona": "T1",
  "pozn": "mensia kapacita; ICO doplnit",
  "lat": 48.374218,
  "lon": 17.5809299
 },
 {
  "kraj": "TT",
  "kat": "Velka restauracia / banketova sala",
  "firma": "Hotel Magnolia Piestany",
  "ico": "doplnit ORSR",
  "adresa": "Nalepkova 1",
  "mesto": "Piestany",
  "okres": "Piestany",
  "velkost": "121 izieb, restauracia 140 + kongresova sala + 2 salonky",
  "tel": "033 762 6251",
  "email": "recepcia@hotelmagnolia.sk",
  "web": "hotelmagnolia.sk",
  "zona": "T3",
  "pozn": "SILNY CIEL; velka kongresova/eventova prevadzka; prevadzkovatel/ICO doplnit ORSR",
  "lat": 48.5874545,
  "lon": 17.8370356
 },
 {
  "kraj": "TT",
  "kat": "Velka restauracia / banketova sala",
  "firma": "Hotel Park Piestany (Kupele)",
  "ico": "doplnit ORSR",
  "adresa": "Nabrezie I. Krasku 2",
  "mesto": "Piestany",
  "okres": "Piestany",
  "velkost": "restauracia 150, kongresove saly, svadby/oslavy",
  "tel": "033 775 5200",
  "email": "",
  "web": "hotelpark.sk",
  "zona": "T3",
  "pozn": "SILNY CIEL; banketove/svadobne + kongresy",
  "lat": 48.595123,
  "lon": 17.839952
 },
 {
  "kraj": "TT",
  "kat": "Velka restauracia / banketova sala",
  "firma": "Hotel sv. Ludmila Skalica",
  "ico": "doplnit ORSR",
  "adresa": "Tehelna 40",
  "mesto": "Skalica",
  "okres": "Skalica",
  "velkost": "restauracia 70; 8 konf. sal ~600 m2, najvacsia do 165",
  "tel": "0910 856 102",
  "email": "info@hotelsvataludmila.sk",
  "web": "hotelsvataludmila.sk",
  "zona": "T5",
  "pozn": "SILNY CIEL; svadby/firemne do 165, najvacsia eventova kapacita v Skalici",
  "lat": 48.835703,
  "lon": 17.2329853
 },
 {
  "kraj": "TT",
  "kat": "Velka restauracia / banketova sala",
  "firma": "Restauracia Jozef II.",
  "ico": "doplnit ORSR",
  "adresa": "Bratislavska 20",
  "mesto": "Holic",
  "okres": "Skalica",
  "velkost": "spolocenska sala 140 miest, parket/ozvucenie/projektor",
  "tel": "034 2028912",
  "email": "",
  "web": "jozefdruhy.sk",
  "zona": "T5",
  "pozn": "SILNY CIEL; banketova/svadobna sala 140, Holic",
  "lat": 48.8022821,
  "lon": 17.1627495
 },
 {
  "kraj": "TT",
  "kat": "Velka restauracia / banketova sala",
  "firma": "Slovensky Dvor Piestany",
  "ico": "doplnit ORSR",
  "adresa": "doplnit",
  "mesto": "Piestany",
  "okres": "Piestany",
  "velkost": "kapacita 150+ osob; firemne party/oslavy/svadby",
  "tel": "",
  "email": "",
  "web": "slovenskydvor.sk",
  "zona": "T3",
  "pozn": "banketove akcie 150+; ICO/adresa over ORSR",
  "lat": 48.5895247,
  "lon": 17.8213848
 },
 {
  "kraj": "TT",
  "kat": "Velka restauracia / banketova sala",
  "firma": "Restauracia Savarin Senica",
  "ico": "doplnit ORSR",
  "adresa": "doplnit",
  "mesto": "Senica",
  "okres": "Senica",
  "velkost": "svadobna sala + klimatizovana sala; svadby/firemne",
  "tel": "",
  "email": "",
  "web": "savarinsenica.com",
  "zona": "T4",
  "pozn": "svadobna sala centrum Senice; kapacita/ICO over",
  "lat": 48.6787557,
  "lon": 17.3661529
 },
 {
  "kraj": "TT",
  "kat": "Velka restauracia / banketova sala",
  "firma": "X-BIONIC SPHERE a.s.",
  "ico": "46640134",
  "adresa": "Dubova 33",
  "mesto": "Samorin",
  "okres": "Dunajska Streda",
  "velkost": "trzby ~18,1 mil EUR; hotel 282 izieb, 5+ restauracii, MICE/eventy",
  "tel": "0904 913037",
  "email": "sales@x-bionicsphere.com",
  "web": "x-bionicsphere.com",
  "zona": "T6",
  "pozn": "SILNY CIEL; obrovsky sportovy rezort, catering pre turnaje/konferencie",
  "lat": 48.0186559,
  "lon": 17.2973262
 },
 {
  "kraj": "TT",
  "kat": "Velka restauracia / banketova sala",
  "firma": "THERMALPARK DS a.s.",
  "ico": "31450920",
  "adresa": "Gabcikovska cesta 38",
  "mesto": "Dunajska Streda",
  "okres": "Dunajska Streda",
  "velkost": "trzby ~9,4 mil EUR (2024); termalny areal + hotel + restauracie/bufety",
  "tel": "",
  "email": "",
  "web": "thermalpark.sk",
  "zona": "T6",
  "pozn": "SILNY CIEL; sezonny velkoobjem; doplnit kontakt",
  "lat": 47.9847932,
  "lon": 17.6086547
 },
 {
  "kraj": "TT",
  "kat": "Velka restauracia / banketova sala",
  "firma": "TERMAL s.r.o. (Thermal Corvinus Velky Meder)",
  "ico": "34099336",
  "adresa": "Promenadna 20",
  "mesto": "Velky Meder",
  "okres": "Dunajska Streda",
  "velkost": "trzby ~8,5 mil EUR; termalne kupalisko + ubytovanie + gastro",
  "tel": "",
  "email": "",
  "web": "thermalcorvinus.eu",
  "zona": "T6",
  "pozn": "SILNY CIEL; velky termalny rezort (vlastnik mesto); viacero stravovacich bodov",
  "lat": 47.8464838,
  "lon": 17.7599623
 },
 {
  "kraj": "TT",
  "kat": "Velka restauracia / banketova sala",
  "firma": "Hotel Thermal Varga s.r.o.",
  "ico": "44497237",
  "adresa": "Promenadna 1",
  "mesto": "Velky Meder",
  "okres": "Dunajska Streda",
  "velkost": "restauracia 120-200 miest, sala + catering",
  "tel": "",
  "email": "",
  "web": "hotelthermal.sk",
  "zona": "T6",
  "pozn": "banketova sala + catering, svadby/konferencie",
  "lat": 47.8480097,
  "lon": 17.7620363
 },
 {
  "kraj": "TT",
  "kat": "Velka restauracia / banketova sala",
  "firma": "Penzion Restauracia MLYN (SLOVFRUCO s.r.o.)",
  "ico": "36276910",
  "adresa": "J. Majku 211",
  "mesto": "Dolna Streda",
  "okres": "Galanta",
  "velkost": "2 saly ~100+50, catering, svadby",
  "tel": "0903 419103",
  "email": "penzionmlyn211@gmail.com",
  "web": "penzionmlyn.sk",
  "zona": "T7",
  "pozn": "banketova sala + catering pri priem. zone Sered",
  "lat": 48.2740853,
  "lon": 17.7448501
 },
 {
  "kraj": "TT",
  "kat": "Velka restauracia / banketova sala",
  "firma": "Restauracia Perlovka (AR GASTRO)",
  "ico": "doplnit ORSR",
  "adresa": "Vinarska 2",
  "mesto": "Sered",
  "okres": "Galanta",
  "velkost": "kompletny servis + catering svadby/firemne/vyrocia",
  "tel": "",
  "email": "argastro.sered@gmail.com",
  "web": "perlovka.sk",
  "zona": "T7",
  "pozn": "banketova/eventova restauracia pri priem. parku Sered; ICO doplnit",
  "lat": 48.285043,
  "lon": 17.7372023
 },
 {
  "kraj": "TT",
  "kat": "Restauracna siet (3+ prevadzok)",
  "firma": "MINIT SLOVAKIA spol. s r.o.",
  "ico": "17053897",
  "adresa": "Muzejna 1",
  "mesto": "Dunajska Streda",
  "okres": "Dunajska Streda",
  "velkost": "trzby 80,5 mil EUR (2025), 500-999 zam; ~350 pekarni MINIT Bakery",
  "tel": "",
  "email": "",
  "web": "minitbakery.sk",
  "zona": "T6",
  "pozn": "SILNY CIEL; sidlo firmy; ~350 pekarni MINIT Bakery (SR), 25+ v TT kraji",
  "lat": 47.996257,
  "lon": 17.6253381
 },
 {
  "kraj": "TT",
  "kat": "Restauracna siet (3+ prevadzok)",
  "firma": "Reston s.r.o. (McDonald's fransiza)",
  "ico": "35795425",
  "adresa": "Hlboka 4",
  "mesto": "Trnava",
  "okres": "Trnava",
  "velkost": "trzby ~30 mil EUR, ~700 zam (TT+BA)",
  "tel": "",
  "email": "",
  "web": "mcdonalds.sk",
  "zona": "T1",
  "pozn": "SILNY CIEL; fransizant McDonald's; majitel Anton Novotny; 3 prevadzky v Trnave (Hlboka 4, Nova, Trstinska)",
  "lat": 48.3815617,
  "lon": 17.593004
 },
 {
  "kraj": "TT",
  "kat": "Restauracna siet (3+ prevadzok)",
  "firma": "COOP Jednota Trnava s.d.",
  "ico": "doplnit ORSR",
  "adresa": "Trojicne namestie 9",
  "mesto": "Trnava",
  "okres": "Trnava",
  "velkost": "viac gastro prevadzok v OD Jednota",
  "tel": "033/324 58 00",
  "email": "",
  "web": "odjednota.sk",
  "zona": "T1",
  "pozn": "sidlo druzstva; viac gastro prevadzok v OD Jednota; ICO druzstva doplnit ORSR",
  "lat": 48.3774728,
  "lon": 17.5874502
 },
 {
  "kraj": "NR",
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Jaguar Land Rover Slovakia s.r.o.",
  "ico": "48302392",
  "adresa": "Horne luky 4540/1",
  "mesto": "Nitra",
  "okres": "Nitra",
  "velkost": "trzby 362,8 mil EUR (2024), 4000-4999 zam",
  "tel": "0800 500 047",
  "email": "hrdirectsk@jaguarlandrover.com",
  "web": "jaguarlandrover.com",
  "zona": "",
  "pozn": "SILNY CIEL; najvacsi zamestnavatel okresu, automobilka, tisice obedov denne v zavodnom stravovani",
  "lat": 48.3458575,
  "lon": 18.0470198
 },
 {
  "kraj": "NR",
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Foxconn Slovakia, spol. s r.o.",
  "ico": "35683724",
  "adresa": "Dolne Hony 29",
  "mesto": "Nitra",
  "okres": "Nitra",
  "velkost": "trzby 558,7 mil EUR (2024), 500-999 zam",
  "tel": "037 6944111",
  "email": "informacie@foxconn.com",
  "web": "foxconn.sk",
  "zona": "",
  "pozn": "SILNY CIEL; velka elektrovyroba v parku Nitra-Sever, smenova prevadzka so zavodnym stravovanim",
  "lat": 48.3270845,
  "lon": 18.0491024
 },
 {
  "kraj": "NR",
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Fakultna nemocnica Nitra",
  "ico": "17336007",
  "adresa": "Spitalska 588/6",
  "mesto": "Nitra",
  "okres": "Nitra",
  "velkost": "vynosy 109,9 mil EUR (2025), 1000-1999 zam, ~1200 lozok",
  "tel": "037 6545111",
  "email": "info@fnnitra.sk",
  "web": "fnnitra.sk",
  "zona": "",
  "pozn": "SILNY CIEL; prispevkova org. s vlastnou kuchynou, denne stravovanie pacientov + personalu, najvacsi gastro objem v okrese",
  "lat": 48.3020114,
  "lon": 18.087383
 },
 {
  "kraj": "NR",
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Miba Steeltec s.r.o.",
  "ico": "36565911",
  "adresa": "Hlavna 48",
  "mesto": "Vrable",
  "okres": "Nitra",
  "velkost": "trzby 103 mil EUR (2025), 500-999 zam",
  "tel": "037 230 15 75",
  "email": "",
  "web": "miba.com",
  "zona": "",
  "pozn": "SILNY CIEL; strojarsky zavod (ocelove diely), smenova prevadzka, vlastne stravovanie",
  "lat": 48.2488025,
  "lon": 18.3025588
 },
 {
  "kraj": "NR",
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Bourbon Automotive Plastics Nitra s.r.o.",
  "ico": "35882409",
  "adresa": "Cab 280",
  "mesto": "Cab",
  "okres": "Nitra",
  "velkost": "trzby 96,6 mil EUR (2025), 500-999 zam",
  "tel": "037 7921111",
  "email": "sekretariat@plastivaloire.com",
  "web": "groupe-plastivaloire.com",
  "zona": "",
  "pozn": "SILNY CIEL; automotive plasty, ~500 zam v zmenovej prevadzke, zavodne stravovanie",
  "lat": 48.4078828,
  "lon": 17.9894147
 },
 {
  "kraj": "NR",
  "kat": "Tackaren / zavodna jedalen",
  "firma": "SMRC Automotive Solutions Slovakia s.r.o.",
  "ico": "36861162",
  "adresa": "Dolne Hony 2",
  "mesto": "Nitra",
  "okres": "Nitra",
  "velkost": "trzby 93,9 mil EUR (2024), 250-499 zam",
  "tel": "",
  "email": "",
  "web": "smrc-automotive.com",
  "zona": "",
  "pozn": "automotive interiery v parku Nitra-Sever, dodavatel JLR, stredny objem stravovania",
  "lat": 48.341425,
  "lon": 18.0640503
 },
 {
  "kraj": "NR",
  "kat": "Tackaren / zavodna jedalen",
  "firma": "G-TEKT Slovakia, s.r.o.",
  "ico": "51087618",
  "adresa": "Na Pasienkoch 9",
  "mesto": "Nitra",
  "okres": "Nitra",
  "velkost": "trzby 64 mil EUR (2024), 250-499 zam",
  "tel": "",
  "email": "",
  "web": "",
  "zona": "",
  "pozn": "automotive karoserne diely, zavod v Nitre, smenova prevadzka",
  "lat": 48.3330772,
  "lon": 18.0578381
 },
 {
  "kraj": "NR",
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Slovenska polnohospodarska univerzita v Nitre - Studentske domovy a jedalne",
  "ico": "00397482",
  "adresa": "Sturova 3",
  "mesto": "Nitra",
  "okres": "Nitra",
  "velkost": "vynosy 46,84 mil EUR (2025), 500-999 zam, vlastna menza",
  "tel": "037 6415701",
  "email": "rsdjspu@uniag.sk",
  "web": "uniag.sk",
  "zona": "",
  "pozn": "SILNY CIEL; vlastne riaditelstvo studentskych jedalni (menza vo vlastnej rezii), priamy kontakt na stravovaci uzol",
  "lat": 48.3066317,
  "lon": 18.087736
 },
 {
  "kraj": "NR",
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Univerzita Konstantina Filozofa v Nitre - Univerzitna jedalen",
  "ico": "00157716",
  "adresa": "Nabrezie mladeze 1",
  "mesto": "Nitra",
  "okres": "Nitra",
  "velkost": "vynosy 41,97 mil EUR (2025), 500-999 zam",
  "tel": "037 6408111",
  "email": "",
  "web": "ukf.sk",
  "zona": "",
  "pozn": "stravovanie outsourcovane (Gastromir, kuchyna SD Brezovy haj); UKF = vlastnik priestoru/odberatel",
  "lat": 48.3176027,
  "lon": 18.0977842
 },
 {
  "kraj": "NR",
  "kat": "Catering dodavatel",
  "firma": "agrokomplex NARODNE VYSTAVISKO, statny podnik",
  "ico": "36855642",
  "adresa": "Vystavna 4",
  "mesto": "Nitra",
  "okres": "Nitra",
  "velkost": "trzby 8,29 mil EUR (2025), 50-99 zam",
  "tel": "037 6572111",
  "email": "agrokomplex@agrokomplex.sk",
  "web": "agrokomplex.sk",
  "zona": "",
  "pozn": "SILNY CIEL; statne vystavisko, vlastny catering pre vystavy/koncerty/konferencie/svadby, sezonne velkokapacitne eventy",
  "lat": 48.3084349,
  "lon": 18.1029376
 },
 {
  "kraj": "NR",
  "kat": "Catering dodavatel",
  "firma": "Golden Catering (esca, s.r.o.)",
  "ico": "46482253",
  "adresa": "Stracia 23",
  "mesto": "Nitra",
  "okres": "Nitra",
  "velkost": "trzby 0,24 mil EUR (2024)",
  "tel": "0950 777 765",
  "email": "info@goldencatering.sk",
  "web": "goldencatering.sk",
  "zona": "",
  "pozn": "20 rokov na trhu, svadby/firemne/VIP catering, prenajom vybavenia; etablovany event dodavatel",
  "lat": 48.2963998,
  "lon": 18.093401
 },
 {
  "kraj": "NR",
  "kat": "Catering dodavatel",
  "firma": "Catering Servis Nitra s. r. o.",
  "ico": "52748561",
  "adresa": "Dumbierska 700/45",
  "mesto": "Nitra",
  "okres": "Nitra",
  "velkost": "trzby 0,05 mil EUR (2025)",
  "tel": "",
  "email": "info@cateringnr.sk",
  "web": "cateringnr.sk",
  "zona": "",
  "pozn": "mensi event/svadobny catering, prevadzkuje aj eventove priestory; doplnkovy ciel",
  "lat": 48.306602,
  "lon": 18.1108036
 },
 {
  "kraj": "NR",
  "kat": "Vyvaren / catering kuchyna",
  "firma": "MS Gastro, s.r.o.",
  "ico": "36359891",
  "adresa": "Velky Lapas 351",
  "mesto": "Velky Lapas",
  "okres": "Nitra",
  "velkost": "trzby 0,78 mil EUR (2025), 5-9 zam",
  "tel": "0904 878 707",
  "email": "msgastro@msgastro.sk",
  "web": "msgastro.sk",
  "zona": "",
  "pozn": "SILNY CIEL; zavodne/firemne stravovanie pre vyrobne firmy v regione, vlastna jedalen + donaska, stabilny velkoodber",
  "lat": 48.2907243,
  "lon": 18.18375
 },
 {
  "kraj": "NR",
  "kat": "Vyvaren / catering kuchyna",
  "firma": "GastroIng (Dagmar Hascakova)",
  "ico": "doplnit ORSR",
  "adresa": "Priemyselna 5",
  "mesto": "Nitra",
  "okres": "Nitra",
  "velkost": "6 hlavnych jedal + polievka denne, zavodna jedalen + rozvoz po Nitre",
  "tel": "037 6574048",
  "email": "",
  "web": "gastroing.sk",
  "zona": "",
  "pozn": "zavodne stravovanie a rozvoz obedov; zivnost, ICO neoverene na FinStat",
  "lat": 48.2899467,
  "lon": 18.0905222
 },
 {
  "kraj": "NR",
  "kat": "Velka restauracia / banketova sala",
  "firma": "Hotel Zlaty Klucik (Golden Key Services, s.r.o.)",
  "ico": "56031173",
  "adresa": "Svaturbanska 103/29",
  "mesto": "Nitra",
  "okres": "Nitra",
  "velkost": "sala do 150 hosti + 2 restauracie + svadobny pavilon, 41 izieb, 4* superior",
  "tel": "037 6550289",
  "email": "recepcia@zlatyklucik.sk",
  "web": "zlatyklucik.sk",
  "zona": "",
  "pozn": "SILNY CIEL; svadobna sala 150 miest, kongresy a eventy, pravidelne velke akcie",
  "lat": 48.31295,
  "lon": 18.0894593
 },
 {
  "kraj": "NR",
  "kat": "Restauracna siet (3+ prevadzok)",
  "firma": "Tantal (Tantal expres 1 s. r. o.)",
  "ico": "47164948",
  "adresa": "Plynarenska 5",
  "mesto": "Nitra",
  "okres": "Nitra",
  "velkost": "4 prevadzky v Nitre (OC Galeria, OC Centro, Kaufland Klokocina + Expres)",
  "tel": "0915 979 065",
  "email": "tantal@tantal.sk",
  "web": "tantal.sk",
  "zona": "",
  "pozn": "talianska kuchyna, 4 prevadzky od 2008, centralny dodavatel surovin",
  "lat": 48.3128581,
  "lon": 18.1190757
 },
 {
  "kraj": "NR",
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Nemocnica AGEL Zlate Moravce a.s.",
  "ico": "50433946",
  "adresa": "Bernolakova 4",
  "mesto": "Zlate Moravce",
  "okres": "Zlate Moravce",
  "velkost": "trzby 7,63 mil EUR (2025), 150-199 zam, 70 lozok",
  "tel": "037 6402111",
  "email": "nemocnicazm@agel.sk",
  "web": "nemocnicazlatemoravce.agel.sk",
  "zona": "",
  "pozn": "SILNY CIEL; vlastna nemocnicna kuchyna, denne stravovanie pacientov + personalu, stabilny odber",
  "lat": 48.383163,
  "lon": 18.3986
 },
 {
  "kraj": "NR",
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Secop s. r. o.",
  "ico": "35800399",
  "adresa": "Tovarenska 49",
  "mesto": "Zlate Moravce",
  "okres": "Zlate Moravce",
  "velkost": "trzby 94,45 mil EUR (2024), 250-499 zam",
  "tel": "",
  "email": "",
  "web": "secop.com",
  "zona": "",
  "pozn": "SILNY CIEL; najvacsi vyrobny zamestnavatel v okrese (kompresory, byv. Nidec/Danfoss), velka zavodna jedalen",
  "lat": 48.3954249,
  "lon": 18.4002148
 },
 {
  "kraj": "NR",
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Estamp Slovakia s.r.o.",
  "ico": "35950765",
  "adresa": "Tovarenska 52",
  "mesto": "Zlate Moravce",
  "okres": "Zlate Moravce",
  "velkost": "trzby 50,10 mil EUR (2024), 200-249 zam",
  "tel": "",
  "email": "",
  "web": "estamp.com",
  "zona": "",
  "pozn": "SILNY CIEL; automotive dodavatel (vylisky), velky zavod v priem. parku, zavodne stravovanie",
  "lat": 48.3923241,
  "lon": 18.3990039
 },
 {
  "kraj": "NR",
  "kat": "Velka restauracia / banketova sala",
  "firma": "Hotel ViOn (ViOn, a.s.)",
  "ico": "36526185",
  "adresa": "Tovarenska 64",
  "mesto": "Zlate Moravce",
  "okres": "Zlate Moravce",
  "velkost": "restauracia 120 miest + kongresova/banketova sala ~130 miest; firma trzby 30,97 mil EUR (2025)",
  "tel": "037 6402471",
  "email": "hotel@vion.sk",
  "web": "hotelvion.sk",
  "zona": "",
  "pozn": "SILNY CIEL; najvacsi hotel+restauracia v meste, svadby/bankety/recepcie, vlastna velka kuchyna",
  "lat": 48.3982894,
  "lon": 18.4053974
 },
 {
  "kraj": "NR",
  "kat": "Catering dodavatel",
  "firma": "GASTRO ABM s. r. o.",
  "ico": "56429096",
  "adresa": "Hlavna 125",
  "mesto": "Tesarske Mlynany",
  "okres": "Zlate Moravce",
  "velkost": "catering + zavodne stravovanie, polievka + 4 hl. jedla denne; firma zal. 2024",
  "tel": "0907 650 755",
  "email": "gastroabm@gastroabm.sk",
  "web": "gastroabm.sk",
  "zona": "",
  "pozn": "SILNY CIEL; dodava zavodne stravovanie firmam, velky denny objem jedal v okrese ZM",
  "lat": 48.3346131,
  "lon": 18.3547198
 },
 {
  "kraj": "NR",
  "kat": "Velka restauracia / banketova sala",
  "firma": "Restauracia RIO (Julia Pivarciova)",
  "ico": "33334595",
  "adresa": "Sladkovicova 37",
  "mesto": "Zlate Moravce",
  "okres": "Zlate Moravce",
  "velkost": "hl. sala 160 miest + terasa 40; zivnostnik",
  "tel": "037 6421343",
  "email": "",
  "web": "",
  "zona": "",
  "pozn": "najvacsia banketova kapacita pre svadby/oslavy v meste (160 miest), sezonny odber pri akciach",
  "lat": 48.3801929,
  "lon": 18.3958499
 },
 {
  "kraj": "NR",
  "kat": "Catering dodavatel",
  "firma": "Restauracia Domino (Ondrej Kozuch)",
  "ico": "41169123",
  "adresa": "SNP 1306",
  "mesto": "Sala",
  "okres": "Sala",
  "velkost": "~85 miest, denny firemny rozvoz obedov + catering + svadobne/smutocne hostiny",
  "tel": "0905 835 102",
  "email": "info@restauraciadomino.sk",
  "web": "restauraciadomino.sk",
  "zona": "",
  "pozn": "catering a pravidelny rozvoz obedov pre firmy, B2B partner pre dodavky surovin",
  "lat": 48.1548103,
  "lon": 17.8723263
 },
 {
  "kraj": "NR",
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Duslo, a.s.",
  "ico": "35826487",
  "adresa": "Administrativna budova ev. c. 1236",
  "mesto": "Sala",
  "okres": "Sala",
  "velkost": "trzby 553,7 mil EUR (2024), 1000-1999 zam",
  "tel": "031 775 1111",
  "email": "sekretariat@duslo.sk",
  "web": "duslo.sk",
  "zona": "",
  "pozn": "SILNY CIEL; najvacsi zamestnavatel v okrese (chemicka), velkoobjemova zavodna jedalen, top objem surovin",
  "lat": 48.15663,
  "lon": 17.89696
 },
 {
  "kraj": "NR",
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Nemocnica s poliklinikou Sala",
  "ico": "00610305",
  "adresa": "Nemocnicna 1",
  "mesto": "Sala",
  "okres": "Sala",
  "velkost": "nemocnica s vlastnou kuchynou, stravovanie pacientov + personalu",
  "tel": "031 7730 320",
  "email": "",
  "web": "poliklinikansksala.sk",
  "zona": "",
  "pozn": "SILNY CIEL; celodenne nemocnicne stravovanie, stabilny velkoodber surovin",
  "lat": 48.1513,
  "lon": 17.8714854
 },
 {
  "kraj": "NR",
  "kat": "Velka restauracia / banketova sala",
  "firma": "Hotel Central (HOTEL CENTRAL ZIBAK COMPANY)",
  "ico": "32361769",
  "adresa": "Nam. Sv. Trojice 3",
  "mesto": "Sala",
  "okres": "Sala",
  "velkost": "banketova sala 150 miest + mensia 40-50, ubytovanie 80 lozok, svadby/bankety/konferencie",
  "tel": "031 770 1141",
  "email": "recepcia@hotelcentral.sk",
  "web": "hotelcentral.sk",
  "zona": "",
  "pozn": "banketova sala v centre Sale, svadby/firemne akcie - pravidelne velke hostiny",
  "lat": 48.1522468,
  "lon": 17.8753827
 },
 {
  "kraj": "NR",
  "kat": "Velka restauracia / banketova sala",
  "firma": "Restaurant Rico (Martina Borikova)",
  "ico": "41171471",
  "adresa": "Jarmocna 626/1",
  "mesto": "Sala",
  "okres": "Sala",
  "velkost": "hlavna sala 131 miest + terasa 50 + salonik 25 (~206), svadby/firemne akcie",
  "tel": "0910 548 517",
  "email": "",
  "web": "restaurantrico.sk",
  "zona": "",
  "pozn": "velkokapacitna restauracia, svadby a firemne eventy - pravidelny odber surovin",
  "lat": 48.1466541,
  "lon": 17.8736525
 },
 {
  "kraj": "NR",
  "kat": "Catering dodavatel",
  "firma": "PARADISE, s.r.o.",
  "ico": "36260339",
  "adresa": "doplnit",
  "mesto": "Kalna nad Hronom",
  "okres": "Levice",
  "velkost": "ostatne ucelove stravovanie, 5-9 zam, prevadzkuje kantinu pri AE Mochovce",
  "tel": "0907 795 223",
  "email": "",
  "web": "",
  "zona": "",
  "pozn": "prevadzkuje zavodnu kantinu Little Paradise pre elektraren Mochovce a dodavatelov - vstup do najvacsieho zamestnavatela v okoli, SILNY CIEL",
  "lat": 48.1997294,
  "lon": 18.5185286
 },
 {
  "kraj": "NR",
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Nemocnica AGEL Levice s.r.o.",
  "ico": "50861450",
  "adresa": "SNP 19",
  "mesto": "Levice",
  "okres": "Levice",
  "velkost": "trzby 40,41 mil EUR (2024), vlastna nemocnicna kuchyna, stovky lozok + personal",
  "tel": "036 6373 111",
  "email": "",
  "web": "nemocnicalevice.agel.sk",
  "zona": "",
  "pozn": "SILNY CIEL; vlastne ustavne stravovanie (pacienti+zamestnanci), denne stovky porcii, siet AGEL",
  "lat": 48.2227843,
  "lon": 18.6145835
 },
 {
  "kraj": "NR",
  "kat": "Tackaren / zavodna jedalen",
  "firma": "ZF Slovakia, a.s. (zavod Levice-Gena)",
  "ico": "36707341",
  "adresa": "Priemyselny park Gena 5654/63",
  "mesto": "Levice",
  "okres": "Levice",
  "velkost": "ZF Slovakia trzby 797 mil EUR (2023), 3000-3999 zam; zavod Levice ~1700 prac. miest, zavodne stravovanie",
  "tel": "036 6357 111",
  "email": "",
  "web": "zf.com",
  "zona": "",
  "pozn": "SILNY CIEL; najvacsi priemyselny zamestnavatel v okrese, zavodna jedalen (sidlo a.s. Trnava, kantina v Leviciach)",
  "lat": 48.2163194,
  "lon": 18.6000869
 },
 {
  "kraj": "NR",
  "kat": "Velka restauracia / banketova sala",
  "firma": "VIALE, s.r.o. (Hotel Lev Levice)",
  "ico": "36567795",
  "adresa": "Csl. armady 2",
  "mesto": "Levice",
  "okres": "Levice",
  "velkost": "spolocenska sala do 350 miest, svadobna do 200; trzby ~695 tis EUR, 20-24 zam",
  "tel": "036 3700 300",
  "email": "recepcia@hotellev.sk",
  "web": "hotellev.sk",
  "zona": "",
  "pozn": "SILNY CIEL; najvacsia banketova/svadobna sala v meste Levice (350 miest), restauracia+kaviaren",
  "lat": 48.2190665,
  "lon": 18.6074125
 },
 {
  "kraj": "NR",
  "kat": "Velka restauracia / banketova sala",
  "firma": "AMALION s.r.o. (Koliba rezort Margita-Ilona)",
  "ico": "36556068",
  "adresa": "Mochovska 30",
  "mesto": "Levice",
  "okres": "Levice",
  "velkost": "trzby 723 503 EUR (2025), 10-19 zam; rezort so salami na svadby/firemne akcie + vinny dom",
  "tel": "036 6316793",
  "email": "amalion@amalion.sk",
  "web": "kolibarezort.sk",
  "zona": "",
  "pozn": "eventovy/svadobny rezort 6 km od Levic, banketove priestory + tradicna kuchyna; objemove svadby a firemne akcie",
  "lat": 48.2024329,
  "lon": 18.6099651
 },
 {
  "kraj": "NR",
  "kat": "Velka restauracia / banketova sala",
  "firma": "HOTELY SK, s.r.o. (Hotel Atom / Restaurant il Caffe)",
  "ico": "36795399",
  "adresa": "Ul. sv. Michala 4",
  "mesto": "Levice",
  "okres": "Levice",
  "velkost": "restauracia 130 miest + 2 terasy, hotel 121 lozok; svadby/oslavy/firemne akcie",
  "tel": "036 6312790",
  "email": "",
  "web": "restaurantilcaffe.sk",
  "zona": "",
  "pozn": "banketova restauracia v centre Levic (130 miest); over aktualny stav hotela pred oslovenim",
  "lat": 48.2163194,
  "lon": 18.6000869
 },
 {
  "kraj": "NR",
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Fakultna nemocnica s poliklinikou Nove Zamky",
  "ico": "17336112",
  "adresa": "Slovenska 5587/11A",
  "mesto": "Nove Zamky",
  "okres": "Nove Zamky",
  "velkost": "trzby 85,33 mil EUR (2024), 1000-1999 zam, 795 lozok, vlastna kuchyna",
  "tel": "035 691 2111",
  "email": "email@nspnz.sk",
  "web": "nspnz.sk",
  "zona": "",
  "pozn": "SILNY CIEL; velka nemocnica, vlastna stravovacia prevadzka pre stovky lozok + zamestnancov, denne velkoobjem",
  "lat": 47.9885036,
  "lon": 18.1535382
 },
 {
  "kraj": "NR",
  "kat": "Velka restauracia / banketova sala",
  "firma": "VADAS, s.r.o. (Vadas Thermal Resort)",
  "ico": "34136215",
  "adresa": "Pri Vadasi 2",
  "mesto": "Sturovo",
  "okres": "Nove Zamky",
  "velkost": "trzby 6,40 mil EUR (2025), 50-99 zam, hotel Thermal 148 lozok + restauracie + bufety, sezonny velkoobjem",
  "tel": "036 7560111",
  "email": "rezervacia@vadas.sk",
  "web": "vadasthermal.sk",
  "zona": "",
  "pozn": "SILNY CIEL; termalny rezort, sezonny napor tisicov navstevnikov, restauracie/bufety/hotel pod jednou firmou",
  "lat": 47.8009942,
  "lon": 18.7163802
 },
 {
  "kraj": "NR",
  "kat": "Velka restauracia / banketova sala",
  "firma": "Termalne kupalisko Podhajska, s.r.o.",
  "ico": "34126040",
  "adresa": "Podhajska 493",
  "mesto": "Podhajska",
  "okres": "Nove Zamky",
  "velkost": "trzby 8,39 mil EUR (2025), 100-149 zam, sezonny velkoobjem, ubytovanie + stravovacie prevadzky",
  "tel": "037 7428023",
  "email": "info@tkpodhajska.sk",
  "web": "tkpodhajska.sk",
  "zona": "",
  "pozn": "SILNY CIEL; velky sezonny navstevnicky objem, viacero stravovacich prevadzok v rezorte",
  "lat": 48.1027332,
  "lon": 18.3442713
 },
 {
  "kraj": "NR",
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Smurfit Westrock Slovakia, a.s.",
  "ico": "36531359",
  "adresa": "Tovarenska 1",
  "mesto": "Sturovo",
  "okres": "Nove Zamky",
  "velkost": "trzby 67,93 mil EUR (2025), 200-249 zam, velky priemyselny zavod so zavodnym stravovanim",
  "tel": "036 7562491",
  "email": "",
  "web": "smurfitkappa.com",
  "zona": "",
  "pozn": "SILNY CIEL; najvacsi zamestnavatel v Sturove (papierne), denna zavodna jedalen pre stovky robotnikov v zmenovej prevadzke",
  "lat": 47.7933976,
  "lon": 18.6954913
 },
 {
  "kraj": "NR",
  "kat": "Vyvaren / catering kuchyna",
  "firma": "GASTRO DOM NZ, s.r.o.",
  "ico": "44881975",
  "adresa": "Komarnanska cesta 13",
  "mesto": "Nove Zamky",
  "okres": "Nove Zamky",
  "velkost": "800+ obedov denne (200 na mieste + rozvoz), 20-24 zam, vlastna sala 150 miest",
  "tel": "0948 028 487",
  "email": "info@gastrodomnz.sk",
  "web": "gastrodomnz.sk",
  "zona": "",
  "pozn": "SILNY CIEL; dodavatel zavodneho/firemneho stravovania 800+ jedal denne, sala 150 miest na bankety/svadby",
  "lat": 47.9724476,
  "lon": 18.1833607
 },
 {
  "kraj": "NR",
  "kat": "Velka restauracia / banketova sala",
  "firma": "Restaurant Michelle Nove Zamky",
  "ico": "doplnit ORSR",
  "adresa": "T. G. Masaryka 31",
  "mesto": "Nove Zamky",
  "okres": "Nove Zamky",
  "velkost": "kapacita 150 miest (sala 262 m2, celk. 600 m2), profi kuchyna + vlastny catering",
  "tel": "0904 365 656",
  "email": "info@michellenovezamky.sk",
  "web": "michellenovezamky.sk",
  "zona": "",
  "pozn": "banketova/svadobna sala v centre, vlastna profi kuchyna a catering - odber surovin vo velkom; ICO doplnit ORSR",
  "lat": 47.994562,
  "lon": 18.1700825
 },
 {
  "kraj": "NR",
  "kat": "Tackaren / zavodna jedalen",
  "firma": "SAM INDUSTRIES a. s. (lodenice Komarno)",
  "ico": "36246093",
  "adresa": "Rolnickej skoly 1519",
  "mesto": "Komarno",
  "okres": "Komarno",
  "velkost": "trzby 68,1 mil EUR (2025), 250-499 zam",
  "tel": "02 209 69 000",
  "email": "info_KN@samindustries.sk",
  "web": "samindustries.sk",
  "zona": "",
  "pozn": "SILNY CIEL; jedina SK lodenica, vyrobny zavod s vlastnym stravovanim; sidlo firmy v BA, prevadzka KN",
  "lat": 47.7629689,
  "lon": 18.1061687
 },
 {
  "kraj": "NR",
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Nemocnica AGEL Komarno s.r.o.",
  "ico": "50828371",
  "adresa": "Medercska 39",
  "mesto": "Komarno",
  "okres": "Komarno",
  "velkost": "trzby 44,54 mil EUR (2024), nemocnica 11 luzkovych oddeleni",
  "tel": "",
  "email": "",
  "web": "nemocnicakomarno.agel.sk",
  "zona": "",
  "pozn": "SILNY CIEL; nemocnica s vlastnou kuchynou, celodenna strava pre pacientov+personal; spadova oblast 110 000 obyv.",
  "lat": 47.76432,
  "lon": 18.126722
 },
 {
  "kraj": "NR",
  "kat": "Velka restauracia / banketova sala",
  "firma": "Termalne kupalisko Komarno (COMORRA SERVIS)",
  "ico": "44191758",
  "adresa": "Vnutorna okruzna 19",
  "mesto": "Komarno",
  "okres": "Komarno",
  "velkost": "trzby 2,30 mil EUR (2024), areal 2,5 ha, 7 bazenov + bufety",
  "tel": "035 7713014",
  "email": "info@thermalkn.sk",
  "web": "thermalkn.sk",
  "zona": "",
  "pozn": "mestska prispevkova org., letna sezona vysoke objemy strediska + bufety/gastro",
  "lat": 47.7572978,
  "lon": 18.1340456
 },
 {
  "kraj": "NR",
  "kat": "Velka restauracia / banketova sala",
  "firma": "Hotel Bow Garden (BOW GARDEN s.r.o.)",
  "ico": "46719253",
  "adresa": "Sturova 1017",
  "mesto": "Komarno",
  "okres": "Komarno",
  "velkost": "hotel + restauracia s terasou, konferencne priestory, bowling/squash/fitness",
  "tel": "",
  "email": "",
  "web": "hotelbowgarden.sk",
  "zona": "",
  "pozn": "banketove/event priestory, restauracia europska kuchyna; B2B suroviny",
  "lat": 47.7604131,
  "lon": 18.1235672
 },
 {
  "kraj": "NR",
  "kat": "Velka restauracia / banketova sala",
  "firma": "Hotel Peklo Komarno",
  "ico": "doplnit ORSR",
  "adresa": "Platanova alej 1",
  "mesto": "Komarno",
  "okres": "Komarno",
  "velkost": "70 luzok, restauracia + wellness, konferencna sala do 70 osob (svadby/seminare)",
  "tel": "035 7740620",
  "email": "recepcia@hotelpeklo.sk",
  "web": "hotelpeklo.sk",
  "zona": "",
  "pozn": "povodny prevadzkovatel DEVILS s.r.o. zruseny 8/2024 - over aktualny subjekt v ORSR; hotel aktivny",
  "lat": 47.7545385,
  "lon": 18.1220248
 },
 {
  "kraj": "NR",
  "kat": "Catering dodavatel",
  "firma": "TOP-DAY catering & vyzdoba (Roman Stevanka)",
  "ico": "doplnit ORSR",
  "adresa": "Nam. M. R. Stefanika 2/6",
  "mesto": "Topolcany",
  "okres": "Topolcany",
  "velkost": "event/svadby/firemny catering, kapacita podla podujatia",
  "tel": "0904 594582",
  "email": "",
  "web": "top-day.sk",
  "zona": "",
  "pozn": "zivnostnik, neoverene ICO na FinStat; svadby+firemne+stuzkove, B2B partner pre suroviny",
  "lat": 48.5590846,
  "lon": 18.1740035
 },
 {
  "kraj": "NR",
  "kat": "Catering dodavatel",
  "firma": "FEAST CATERING",
  "ico": "doplnit ORSR",
  "adresa": "doplnit",
  "mesto": "Topolcany",
  "okres": "Topolcany",
  "velkost": "8+ rokov, oblozene misy + catering na podujatia",
  "tel": "",
  "email": "",
  "web": "feastcatering.sk",
  "zona": "",
  "pozn": "mensi catering, B2B suroviny; ICO neoverene na FinStat",
  "lat": 48.5594345,
  "lon": 18.1754394
 },
 {
  "kraj": "NR",
  "kat": "Tackaren / zavodna jedalen",
  "firma": "HYZA a.s.",
  "ico": "31562540",
  "adresa": "Odbojarov 2279/37",
  "mesto": "Topolcany",
  "okres": "Topolcany",
  "velkost": "trzby 131,3 mil EUR (2024), 500-999 zam",
  "tel": "038 53 722 36",
  "email": "sekretariat@hyza.sk",
  "web": "hyza.sk",
  "zona": "",
  "pozn": "SILNY CIEL; najvacsi spracovatel hydiny, 900+ ludi, vlastna zavodna jedalen; skupina AGROFERT",
  "lat": 48.5606794,
  "lon": 18.138358
 },
 {
  "kraj": "NR",
  "kat": "Tackaren / zavodna jedalen",
  "firma": "DECODOM, spol. s r.o.",
  "ico": "36305073",
  "adresa": "Pilska 7",
  "mesto": "Topolcany",
  "okres": "Topolcany",
  "velkost": "trzby 33,84 mil EUR (2024), 250-499 zam",
  "tel": "",
  "email": "",
  "web": "decodom.sk",
  "zona": "",
  "pozn": "SILNY CIEL; najvacsi SK vyrobca nabytku, vyroba v TO, zavodne stravovanie; firma v restrukturalizacii (over solventnost)",
  "lat": 48.5666108,
  "lon": 18.165336
 },
 {
  "kraj": "NR",
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Nemocnica Topolcany, a. s. (Penta/Svet zdravia)",
  "ico": "46458581",
  "adresa": "Pavlovova 17",
  "mesto": "Topolcany",
  "okres": "Topolcany",
  "velkost": "trzby 29,69 mil EUR, akutna nemocnica",
  "tel": "",
  "email": "",
  "web": "pentahospitals.sk",
  "zona": "",
  "pozn": "SILNY CIEL; nemocnicna kuchyna, celodenne stravovanie pacientov+zamestnancov; siet Penta Hospitals",
  "lat": 48.5521333,
  "lon": 18.1677687
 },
 {
  "kraj": "NR",
  "kat": "Velka restauracia / banketova sala",
  "firma": "Mestske sluzby Topolcany, s.r.o.",
  "ico": "44818378",
  "adresa": "Nam. M. R. Stefanika 1/1",
  "mesto": "Topolcany",
  "okres": "Topolcany",
  "velkost": "mestska s.r.o., kryta plavaren + letne kupalisko, kapacita 160+",
  "tel": "",
  "email": "",
  "web": "sluzbyto.sk",
  "zona": "",
  "pozn": "sezonne gastro/bufet na kupaliskach, mestsky prevadzkovatel",
  "lat": 48.5585009,
  "lon": 18.1741558
 },
 {
  "kraj": "NR",
  "kat": "Velka restauracia / banketova sala",
  "firma": "Hotel Novy Kastiel Topolcany",
  "ico": "doplnit ORSR",
  "adresa": "doplnit",
  "mesto": "Topolcany",
  "okres": "Topolcany",
  "velkost": "3* business hotel pri centre, restauracia, vhodny na firemne podujatia",
  "tel": "",
  "email": "",
  "web": "novykastiel.sk",
  "zona": "",
  "pozn": "event/firemne priestory; ICO neoverene na FinStat (over presny prevadzkovy subjekt)",
  "lat": 48.5594345,
  "lon": 18.1754394
 }
];
