const GASTRO_DATA = [
 {
  "kat": "Vyvaren / catering kuchyna",
  "firma": "Delirest Slovakia s.r.o. (brand EUREST)",
  "ico": "31342809",
  "adresa": "Plynarenska 7/B",
  "mesto": "Bratislava-Ruzinov",
  "okres": "Bratislava",
  "velkost": "LIDER: 35,5 mil EUR, 500-999 zam",
  "tel": "",
  "email": "",
  "web": "eurest.sk",
  "zona": "Z2",
  "pozn": "tel/email cez ORSR (web docasne down)",
  "lat": 48.1455454,
  "lon": 17.143422
 },
 {
  "kat": "Vyvaren / catering kuchyna",
  "firma": "FOOD TIME s.r.o.",
  "ico": "52079881",
  "adresa": "Lozorno 995 (prevadzka)",
  "mesto": "Lozorno",
  "okres": "Malacky",
  "velkost": "~5,2 mil EUR (2023); 10000+ porcii/den",
  "tel": "+421 918 797 063",
  "email": "obchod@food-time.sk",
  "web": "food-time.sk",
  "zona": "Z6",
  "pozn": "najvyssia kapacita; sidlo Tren. Teplice, prevadzka v BA kraji",
  "lat": 48.3346371,
  "lon": 17.0444471
 },
 {
  "kat": "Vyvaren / catering kuchyna",
  "firma": "GTH catering s.r.o. (ex-Sodexo)",
  "ico": "35728434",
  "adresa": "Vajnorska 100/B",
  "mesto": "Bratislava-Nove Mesto",
  "okres": "Bratislava",
  "velkost": "7,1 mil EUR, 150-199 zam",
  "tel": "",
  "email": "",
  "web": "gthcatering.sk",
  "zona": "Z2",
  "pozn": "sidlo sa stahuje do Nitry od 1.6.2026",
  "lat": 48.1698902,
  "lon": 17.140156
 },
 {
  "kat": "Vyvaren / catering kuchyna",
  "firma": "SHARKAM B&B Catering s.r.o.",
  "ico": "46844341",
  "adresa": "Krokusova 3 (kanc. Technopol, Kutlikova 17)",
  "mesto": "Bratislava-Petrzalka",
  "okres": "Bratislava",
  "velkost": "3,4 mil EUR; jedalen 850 ludi/den",
  "tel": "+421 915 763 073",
  "email": "bankovich@sharkam.eu",
  "web": "sharkam.eu",
  "zona": "Z3",
  "pozn": "jedalen Technopol + protokolarny catering",
  "lat": 48.1352541,
  "lon": 17.1152978
 },
 {
  "kat": "Vyvaren / catering kuchyna",
  "firma": "RC Slovakia s.r.o. (SKIES Catering)",
  "ico": "35870362",
  "adresa": "Vajnorska 100/B",
  "mesto": "Bratislava-Nove Mesto",
  "okres": "Bratislava",
  "velkost": "1,2 mil EUR; ISO/IFS/BRC",
  "tel": "+421 911 713 000",
  "email": "javorkova@rcslovakia.sk",
  "web": "rcslovakia.sk",
  "zona": "Z2",
  "pozn": "eventy, kongresy",
  "lat": 48.1698902,
  "lon": 17.140156
 },
 {
  "kat": "Vyvaren / catering kuchyna",
  "firma": "Timeout Catering s.r.o.",
  "ico": "55083561",
  "adresa": "Polna 4",
  "mesto": "Senec",
  "okres": "Senec",
  "velkost": "event do 1000 ludi",
  "tel": "+421 918 227 782",
  "email": "info@timeoutcatering.sk",
  "web": "timeoutcatering.sk",
  "zona": "Z8",
  "pozn": "pokryva BA + Senec + Pezinok",
  "lat": 48.2086452,
  "lon": 17.4018888
 },
 {
  "kat": "Vyvaren / catering kuchyna",
  "firma": "PINO group s.r.o.",
  "ico": "44013141",
  "adresa": "Kadnarova 99",
  "mesto": "Bratislava-Raca",
  "okres": "Bratislava",
  "velkost": "skolske + firemne jedalne",
  "tel": "+421 904 884 427",
  "email": "objednavky@pinostravovanie.sk",
  "web": "pinostravovanie.sk",
  "zona": "Z2",
  "pozn": "17+ rokov",
  "lat": 48.2053369,
  "lon": 17.1465294
 },
 {
  "kat": "Vyvaren / catering kuchyna",
  "firma": "Oldeji (J. Cerna Szalay, zivnost)",
  "ico": "32212721",
  "adresa": "Rusovska cesta 3903/50",
  "mesto": "Bratislava-Petrzalka",
  "okres": "Bratislava",
  "velkost": "vlastna kuchyna od 1994, 10-19 zam",
  "tel": "0904 630 487",
  "email": "info@oldeji.sk",
  "web": "oldeji.sk",
  "zona": "Z3",
  "pozn": "rozvoz v termonadobach + prevadzka jedalni",
  "lat": 48.1235338,
  "lon": 17.1089883
 },
 {
  "kat": "Vyvaren / catering kuchyna",
  "firma": "ALFA FOOD vzs s.r.o.",
  "ico": "55167071",
  "adresa": "Zilinska 7028/1",
  "mesto": "Bratislava-Stare Mesto",
  "okres": "Bratislava",
  "velkost": "0,62 mil EUR (2024), 25-49 zam",
  "tel": "+421 903 995 595",
  "email": "info@alfafood.sk",
  "web": "alfafood.sk",
  "zona": "Z1",
  "pozn": "zavodne stravovanie",
  "lat": 48.1545738,
  "lon": 17.1112842
 },
 {
  "kat": "Vyvaren / catering kuchyna",
  "firma": "ProZeta s.r.o. (Happy Day Catering)",
  "ico": "36739499",
  "adresa": "Padlych hrdinov 24",
  "mesto": "Bratislava-Podunajske Biskupice",
  "okres": "Bratislava",
  "velkost": "svadby, eventy, firmy",
  "tel": "0948 080 180",
  "email": "info@happy-day.sk",
  "web": "happydaycatering.sk",
  "zona": "Z5",
  "pozn": "16+ rokov",
  "lat": 48.1237261,
  "lon": 17.2123351
 },
 {
  "kat": "Vyvaren / catering kuchyna",
  "firma": "TOVAR a SLUZBY s.r.o. (Jedlo Bratislava)",
  "ico": "51725053",
  "adresa": "Popovova 8 (kuchyna Dr. V. Clementisa 5)",
  "mesto": "Bratislava-Ruzinov",
  "okres": "Bratislava",
  "velkost": "rozvoz obedov",
  "tel": "0905 600 000",
  "email": "",
  "web": "jedlobratislava.sk",
  "zona": "Z2",
  "pozn": "rozvoz po celej BA vratane noci",
  "lat": 48.1608571,
  "lon": 17.1477295
 },
 {
  "kat": "Vyvaren / catering kuchyna",
  "firma": "OXA Delivery Service s.r.o.",
  "ico": "50293231",
  "adresa": "Stredna 1",
  "mesto": "Bratislava-Ruzinov",
  "okres": "Bratislava",
  "velkost": "0,6 mil EUR (2024), 5-9 zam",
  "tel": "",
  "email": "",
  "web": "",
  "zona": "Z2",
  "pozn": "catering pre materske skoly; kontakt cez ORSR",
  "lat": 48.1763819,
  "lon": 17.1703672
 },
 {
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Eat & Meet - Mlynska dolina (UK)",
  "ico": "",
  "adresa": "Stare Grunty, blok AD-U, Mlynska dolina",
  "mesto": "Bratislava-Karlova Ves",
  "okres": "Bratislava",
  "velkost": "450 miest, 4000+ jedal/den (areal Mlyny az 6000)",
  "tel": "",
  "email": "",
  "web": "eatandmeet.sk",
  "zona": "Z4",
  "pozn": "univerzitna; vlastna prevadzka UK",
  "lat": 48.1641859,
  "lon": 17.0678683
 },
 {
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Venza - Mlyny UK",
  "ico": "",
  "adresa": "Mlynska dolina",
  "mesto": "Bratislava-Karlova Ves",
  "okres": "Bratislava",
  "velkost": "sucast arealu Mlyny (6000/den)",
  "tel": "",
  "email": "",
  "web": "mlyny.uniba.sk",
  "zona": "Z4",
  "pozn": "univerzitna jedalen",
  "lat": 48.1548435,
  "lon": 17.06991
 },
 {
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Jedalen EUBA - Dolnozemska (City Gastro)",
  "ico": "",
  "adresa": "Dolnozemska cesta 1",
  "mesto": "Bratislava-Petrzalka",
  "okres": "Bratislava",
  "velkost": "500 miest / 1500 pri recepcii",
  "tel": "+421 948 929 323",
  "email": "sekretariat@citygastro.sk",
  "web": "citygastro.sk",
  "zona": "Z3",
  "pozn": "prevadzkuje City Gastro",
  "lat": 48.1275493,
  "lon": 17.1323468
 },
 {
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Jedalen Mlada garda (STU)",
  "ico": "",
  "adresa": "Racianska 103",
  "mesto": "Bratislava-Nove Mesto",
  "okres": "Bratislava",
  "velkost": "136 miest + siet 5-7 jedalni STU",
  "tel": "+421 918 600 162",
  "email": "",
  "web": "stuba.sk",
  "zona": "Z2",
  "pozn": "UZ SDaJ STU",
  "lat": 48.177312,
  "lon": 17.1261017
 },
 {
  "kat": "Tackaren / zavodna jedalen",
  "firma": "UNB - Nemocnica Ruzinov",
  "ico": "",
  "adresa": "Ruzinovska 6",
  "mesto": "Bratislava-Ruzinov",
  "okres": "Bratislava",
  "velkost": ">100k hospitalizacii/rok",
  "tel": "02 48234111",
  "email": "",
  "web": "unb.sk",
  "zona": "Z2",
  "pozn": "vlastna OLVaS; vstup cez verejne obstaravanie",
  "lat": 48.1552301,
  "lon": 17.1519477
 },
 {
  "kat": "Tackaren / zavodna jedalen",
  "firma": "UNB - Nem. ak. L. Derera (Kramare)",
  "ico": "",
  "adresa": "Limbova 5",
  "mesto": "Bratislava-Nove Mesto",
  "okres": "Bratislava",
  "velkost": "velka nemocnica",
  "tel": "",
  "email": "",
  "web": "unb.sk",
  "zona": "Z2",
  "pozn": "vlastna kuchyna, tacovy system",
  "lat": 48.1662606,
  "lon": 17.0863257
 },
 {
  "kat": "Tackaren / zavodna jedalen",
  "firma": "UNB - Nem. sv. Cyrila a Metoda (Petrzalka)",
  "ico": "",
  "adresa": "Antolska 11",
  "mesto": "Bratislava-Petrzalka",
  "okres": "Bratislava",
  "velkost": "velka nemocnica",
  "tel": "",
  "email": "",
  "web": "unb.sk",
  "zona": "Z3",
  "pozn": "vlastna kuchyna",
  "lat": 48.1020874,
  "lon": 17.1183618
 },
 {
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Narodny ustav srdc. a cievnych chorob (NUSCH)",
  "ico": "",
  "adresa": "Pod Krasnou horkou 1",
  "mesto": "Bratislava-Kramare",
  "okres": "Bratislava",
  "velkost": "vlastna kuchyna",
  "tel": "",
  "email": "",
  "web": "nusch.sk",
  "zona": "Z2",
  "pozn": "",
  "lat": 48.1696588,
  "lon": 17.0869479
 },
 {
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Narodny onkologicky ustav (NOU)",
  "ico": "",
  "adresa": "Klenova 1",
  "mesto": "Bratislava-Kramare",
  "okres": "Bratislava",
  "velkost": "vlastna kuchyna, ~200+ lozok",
  "tel": "",
  "email": "",
  "web": "nou.sk",
  "zona": "Z2",
  "pozn": "",
  "lat": 48.1718244,
  "lon": 17.0894784
 },
 {
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Nemocnica sv. Michala",
  "ico": "",
  "adresa": "Satinskeho I. 1",
  "mesto": "Bratislava-Stare Mesto",
  "okres": "Bratislava",
  "velkost": "vlastna OLVaS",
  "tel": "",
  "email": "",
  "web": "nsmas.sk",
  "zona": "Z1",
  "pozn": "vojensko-policajna univ. nemocnica",
  "lat": 48.1452492,
  "lon": 17.1175227
 },
 {
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Volkswagen Slovakia - zavodna jedalen",
  "ico": "",
  "adresa": "Jana Jonasa 1",
  "mesto": "Bratislava-Devinska Nova Ves",
  "okres": "Bratislava",
  "velkost": "NAJVACSI CIEL: ~11-13 tis. zamestnancov",
  "tel": "",
  "email": "facility/HR",
  "web": "volkswagen.sk",
  "zona": "Z4",
  "pozn": "operator stravovania NEOVERENY - priamy dopyt",
  "lat": 48.2350546,
  "lon": 16.9817538
 },
 {
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Slovnaft - zavodna jedalen",
  "ico": "",
  "adresa": "Vlcie hrdlo 1",
  "mesto": "Bratislava-Ruzinov",
  "okres": "Bratislava",
  "velkost": "velky priemyselny zavod",
  "tel": "",
  "email": "facility",
  "web": "slovnaft.sk",
  "zona": "Z5",
  "pozn": "operator neovereny",
  "lat": 48.1282386,
  "lon": 17.176661
 },
 {
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Mondelez SR Production - kantina",
  "ico": "",
  "adresa": "Racianska 44",
  "mesto": "Bratislava-Raca",
  "okres": "Bratislava",
  "velkost": "~400 zamestnancov",
  "tel": "",
  "email": "",
  "web": "",
  "zona": "Z2",
  "pozn": "cokoladovna",
  "lat": 48.1932309,
  "lon": 17.1416428
 },
 {
  "kat": "Tackaren / zavodna jedalen",
  "firma": "La Cantina - Tatracentrum (Bencik)",
  "ico": "",
  "adresa": "Hodzovo nam. 3",
  "mesto": "Bratislava-Stare Mesto",
  "okres": "Bratislava",
  "velkost": "BC kantina",
  "tel": "",
  "email": "",
  "web": "bencikculinary.sk",
  "zona": "Z1",
  "pozn": "siet kantin v BC (Central, Apollo, Petrzalka)",
  "lat": 48.1484131,
  "lon": 17.1087896
 },
 {
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Food Season - Westend Square",
  "ico": "",
  "adresa": "Dubravska cesta 2",
  "mesto": "Bratislava-Karlova Ves",
  "okres": "Bratislava",
  "velkost": "firemna kantina",
  "tel": "",
  "email": "",
  "web": "foodseason.sk",
  "zona": "Z4",
  "pozn": "bio suroviny, sous-vide",
  "lat": 48.1686969,
  "lon": 17.0753887
 },
 {
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Canteen Priatelia - Westend Tower",
  "ico": "",
  "adresa": "Dubravska cesta 2",
  "mesto": "Bratislava-Karlova Ves",
  "okres": "Bratislava",
  "velkost": "firemna kantina",
  "tel": "",
  "email": "",
  "web": "",
  "zona": "Z4",
  "pozn": "",
  "lat": 48.1686969,
  "lon": 17.0753887
 },
 {
  "kat": "Tackaren / zavodna jedalen",
  "firma": "Fajne Jedlo - Tower 115",
  "ico": "",
  "adresa": "Pribinova 25",
  "mesto": "Bratislava-Stare Mesto",
  "okres": "Bratislava",
  "velkost": "samoobsluzna kantina",
  "tel": "",
  "email": "",
  "web": "",
  "zona": "Z1",
  "pozn": "zona Eurovea/Twin City",
  "lat": 48.1411404,
  "lon": 17.1273381
 }
];
